// 由 tools/gen_data.py 从 research/lab 的实测原文与真实产物生成，不要手改
window.DATA = {
 "srlua": {
  "make": [
   "gcc -std=c99 -Wall -Wextra -Wfatal-errors -O2 -o srglue srglue.c",
   "gcc -std=c99 -Wall -Wextra -Wfatal-errors -O2 -I/usr/include -o srlua srlua.c -L/usr/lib64 -llua -lm -ldl -Wl,-E"
  ],
  "glue_cmd": "/home/waterrun/srlua-103/srglue /home/waterrun/srlua-103/srlua main.lua moon-srlua",
  "run_here": [
   "2026-10-01  waning gibbous  78% lit"
  ],
  "elsewhere": [
   "/home/waterrun/moon/moon-srlua: :2: module 'moon.phase' not found:",
   "\tno field package.preload['moon.phase']",
   "\tno file '/usr/share/lua/5.4/moon/phase.lua'"
  ],
  "path": [
   "moon-srlua: cannot open moon-srlua: No such file or directory"
  ],
  "nolib": [
   "./moon-srlua: error while loading shared libraries: liblua-5.4.so: cannot open shared object file: No such file or directory"
  ],
  "ldd": [
   "\tlinux-vdso.so.1 (0x00007fa3bd6d8000)",
   "\tliblua-5.4.so => /lib64/liblua-5.4.so (0x00007fa3bd688000)",
   "\tlibm.so.6 => /lib64/libm.so.6 (0x00007fa3bd571000)",
   "\tlibc.so.6 => /lib64/libc.so.6 (0x00007fa3bd378000)",
   "\t/lib64/ld-linux-x86-64.so.2 (0x00007fa3bd6da000)"
  ],
  "size": 14443
 },
 "luastatic": {
  "cmd": "luastatic main.lua moon/phase.lua moon/julian.lua moon/names.lua /usr/lib64/liblua.a",
  "out": [
   "cc -Os main.luastatic.c  /usr/lib64/liblua.a -rdynamic -lm -ldl -o main"
  ],
  "short_cmd": "luastatic main.lua /usr/lib64/liblua.a",
  "short_out": [
   "cc -Os main.luastatic.c  /usr/lib64/liblua.a -rdynamic -lm -ldl -o main"
  ],
  "short_run": [
   "[string \"main\"]:2: module 'moon.phase' not found:",
   "\tno field package.preload['moon.phase']",
   "\tno module 'moon.phase' in luastatic bundle"
  ],
  "nolua_cmd": "luastatic main.lua moon/phase.lua moon/julian.lua moon/names.lua",
  "nolua_out": [
   "cc -Os main.luastatic.c   -rdynamic -lm  -o main",
   "/usr/bin/ld.bfd: /tmp/ccXk7MVb.o: in function `lstop':",
   "main.luastatic.c:(.text+0x30): undefined reference to `lua_sethook'"
  ],
  "undefined": 44,
  "sizes": {
   "main": 1303640,
   "main.luastatic.c": 21735
  },
  "usage4": "[4]: One or more static libraries for a required Lua binary module"
 },
 "len": {
  "luastatic": 84,
  "luai": 16
 },
 "luai_short": {
  "cmd": "luai -b main.lua",
  "out": [
   "ok",
   "executable: /home/waterrun/moon/build/main/main"
  ]
 },
 "clean": {
  "lua": [
   "bash: lua: command not found"
  ],
  "lua_main": [
   "bash: lua: command not found"
  ],
  "moon": [
   "2026-10-01  waning gibbous  78% lit"
  ],
  "onefile": [
   "2026-10-01  waning gibbous  78% lit"
  ],
  "ldd": [
   "\tliblua-5.4.so => /root/a/moon/build/moon/.luai/native/liblua-5.4.so (0x00007fceb3ad3000)"
  ]
 },
 "ltokei": [
  "Language  Files  Lines  Blank  Comment  Code",
  "--------  -----  -----  -----  -------  -----",
  "C         1      251    21     3        227",
  "Lua       23     15877  1215   793      13869",
  "Total     24     16128  1236   796      14096"
 ],
 "install": {
  "rocks": [
   "Installing https://luarocks.org/luainstaller-1.4.0-1.src.rock",
   "luainstaller 1.4.0-1 is now installed in /usr (license: LGPL-3.0-or-later)"
  ],
  "version": [
   "luai 1.4.0"
  ],
  "version_long": [
   "luainstaller 1.4.0  LGPL 3.0 by WaterRun"
  ],
  "standalone_cmd": "lua tools/install.lua --prefix /home/waterrun/luainstaller",
  "standalone": [
   "Installed luainstaller 1.4.0 into /home/waterrun/luainstaller",
   "Add to PATH: /home/waterrun/luainstaller/bin",
   "Library: add /home/waterrun/luainstaller/?.lua to package.path"
  ],
  "help": [
   "Usage: luai -h",
   "       luai -v",
   "       luai -a <entry.lua> [options]",
   "       luai -t <entry.lua> [options]",
   "       luai -b <entry.lua> [options]",
   "Commands:",
   "  -a <entry.lua>    analyze dependencies",
   "  -t <entry.lua>    trace dependency resolution",
   "  -b <entry.lua>    build a bundle",
   "Options:",
   "  --dir, --onedir       directory bundle mode",
   "  --file, --onefile     self-extracting single-file mode",
   "  -o, --out <path>      output path",
   "  --include <path>      include an extra file",
   "  --exclude <path>      exclude a dependency",
   "  --target-os <os>      assert the detected native host OS",
   "  --lua <path>          Lua interpreter for runtime discovery",
   "  --lua-prefix <path>   matching native Lua headers/runtime prefix",
   "  -d, --discovery-mode <mode>",
   "                        static, manual, or runtime",
   "  --no-depscan          manual dependencies only",
   "  --max-deps <n>        dependency count limit",
   "  --verbose             more detail"
  ],
  "help_raw": [
   "Usage: luai -h",
   "       luai -v",
   "       luai -a <entry.lua> [options]",
   "       luai -t <entry.lua> [options]",
   "       luai -b <entry.lua> [options]",
   "",
   "Commands:",
   "  -a <entry.lua>    analyze dependencies",
   "  -t <entry.lua>    trace dependency resolution",
   "  -b <entry.lua>    build a bundle",
   "",
   "Options:",
   "  --dir, --onedir       directory bundle mode",
   "  --file, --onefile     self-extracting single-file mode",
   "  -o, --out <path>      output path",
   "  --include <path>      include an extra file",
   "  --exclude <path>      exclude a dependency",
   "  --target-os <os>      assert the detected native host OS",
   "  --lua <path>          Lua interpreter for runtime discovery",
   "  --lua-prefix <path>   matching native Lua headers/runtime prefix",
   "  -d, --discovery-mode <mode>",
   "                        static, manual, or runtime",
   "  --no-depscan          manual dependencies only",
   "  --max-deps <n>        dependency count limit",
   "  --verbose             more detail"
  ],
  "mix": [
   [
    "error: unknown luai command: build",
    "try: luai -h"
   ],
   [
    "error: unknown luainstaller command: -b",
    "hint: run `luainstaller help`"
   ]
  ]
 },
 "prereq": {
  "analyze": [
   "ok",
   "entry: main.lua",
   "scripts: 3",
   "libraries: 0",
   "script[1]: /home/waterrun/moon/moon/julian.lua",
   "script[2]: /home/waterrun/moon/moon/phase.lua",
   "script[3]: /home/waterrun/moon/moon/names.lua"
  ],
  "build_fail": [
   "error: ToolchainError: No Lua development metadata matches the selected ABI"
  ],
  "build_fail2": [
   "error: ToolchainError: No Lua development metadata matches the selected ABI"
  ],
  "build_ok": [
   "ok",
   "executable: /home/waterrun/moon/build/moon/moon"
  ],
  "which1": [
   "which: no cc in (/home/waterrun/luainstaller/bin:/usr/local/bin:/usr/bin)",
   "which: no gcc in (/home/waterrun/luainstaller/bin:/usr/local/bin:/usr/bin)",
   "which: no luarocks in (/home/waterrun/luainstaller/bin:/usr/local/bin:/usr/bin)"
  ]
 },
 "versions": {
  "lua": "5.4.8",
  "gcc": "16.2.1",
  "lua_v": "Lua 5.4.8  Copyright (C) 1994-2025 Lua.org, PUC-Rio"
 },
 "cmd": {
  "lua main.lua 2026-10-01": [
   "2026-10-01  waning gibbous  78% lit"
  ],
  "luai -a main.lua": [
   "ok",
   "entry: main.lua",
   "scripts: 3",
   "libraries: 0",
   "script[1]: /home/waterrun/moon/moon/julian.lua",
   "script[2]: /home/waterrun/moon/moon/phase.lua",
   "script[3]: /home/waterrun/moon/moon/names.lua"
  ],
  "luainstaller analyze main.lua": [
   "Analysis complete",
   "  Entry: main.lua",
   "  Lua scripts: 3",
   "  Native libraries: 0"
  ],
  "luai -t main.lua": [
   "trace",
   "entry: main.lua",
   "1: lua resolved moon.phase -> /home/waterrun/moon/moon/phase.lua",
   "2: lua resolved moon.julian -> /home/waterrun/moon/moon/julian.lua",
   "3: lua resolved moon.names -> /home/waterrun/moon/moon/names.lua",
   "compatibility: same OS, same architecture, same ABI, same Lua ABI",
   "note: does not claim universal cross-platform output",
   "note: requires same OS, same architecture, same ABI, and same Lua ABI",
   "note: runtime require discovery only covers build-time executed code paths",
   "note: POSIX bundles select shared or static Lua through compile-and-run capability probes"
  ],
  "luainstaller trace main.lua": [
   "Dependency trace",
   "  Entry: main.lua",
   "  1. lua  resolved  moon.phase -> /home/waterrun/moon/moon/phase.lua",
   "  2. lua  resolved  moon.julian -> /home/waterrun/moon/moon/julian.lua",
   "  3. lua  resolved  moon.names -> /home/waterrun/moon/moon/names.lua",
   "Compatibility",
   "  same OS, same architecture, same ABI, same Lua ABI",
   "  note: does not claim universal cross-platform output",
   "  note: requires same OS, same architecture, same ABI, and same Lua ABI",
   "  note: runtime require discovery only covers build-time executed code paths",
   "  note: POSIX bundles select shared or static Lua through compile-and-run capability probes"
  ],
  "ls -l build/moon": [
   "total 28",
   "-rw-r--r--. 1 waterrun waterrun  2006 Oct  1 09:23 THIRD_PARTY_NOTICES.md",
   "-rwxr-xr-x. 1 waterrun waterrun 22472 Oct  1 09:23 moon"
  ],
  "env -u LUA_PATH -u LUA_CPATH build/moon/moon 2026-10-01": [
   "2026-10-01  waning gibbous  78% lit"
  ],
  "env -i build/moon/moon 2026-10-01": [
   "2026-10-01  waning gibbous  78% lit"
  ],
  "ldd build/moon/moon": [
   "\tlinux-vdso.so.1 (0x00007f17ce050000)",
   "\tliblua-5.4.so => /home/waterrun/moon/build/moon/.luai/native/liblua-5.4.so (0x00007f17ce003000)",
   "\tlibm.so.6 => /lib64/libm.so.6 (0x00007f17cdee9000)",
   "\tlibc.so.6 => /lib64/libc.so.6 (0x00007f17cdcf0000)",
   "\t/lib64/ld-linux-x86-64.so.2 (0x00007f17ce052000)"
  ],
  "file build/moon/moon": [
   "build/moon/moon: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=7093e02b2c91b4aa6fcd82a1ee8f5abe7e51cf94, for GNU/Linux 3.2.0, not stripped"
  ],
  "ls -l build": [
   "total 476",
   "drwx------. 1 waterrun waterrun     62 Oct  1 09:23 moon",
   "-rwxr-xr-x. 1 waterrun waterrun 486280 Oct  1 09:23 moon-onefile"
  ],
  "ldd build/moon-onefile": [
   "\tlinux-vdso.so.1 (0x00007f5d70a17000)",
   "\tlibc.so.6 => /lib64/libc.so.6 (0x00007f5d70813000)",
   "\t/lib64/ld-linux-x86-64.so.2 (0x00007f5d70a19000)"
  ],
  "luainstaller logs --limit 6": [
   "Showing 6 log(s)",
   "  [2026-10-01T09:24:16Z] error   api:analyze Dynamic require at /home/waterrun/dyn/main.lua:2: require('drivers.' .. ...)",
   "Only static require('name') is supported.",
   "  [2026-10-01T09:24:16Z] error   api:bundle unknown option: colour",
   "  [2026-10-01T09:24:07Z] error   api:bundle Lua prefix does not contain development files for the selected Lua ABI",
   "  [2026-10-01T09:24:07Z] error   api:analyze Dynamic require at /home/waterrun/dyn/main.lua:2: require('drivers.' .. ...)",
   "Only static require('name') is supported.",
   "  [2026-10-01T09:24:07Z] error   api:bundle Lua script not found: nothere.lua",
   "  [2026-10-01T09:24:07Z] error   api:analyze Cannot resolve module 'not.installed' required in /home/waterrun/missing/main.lua",
   "Searched: /home/waterrun/missing, /home/waterrun/missing/src, /home/waterrun/missing/lib, /home/waterrun/missing/lua_modules, /usr/share/lua/5.4, /usr/lib64/lua/5.4, ., /home/waterrun/.luarocks/share/lua/5.4, /home/waterrun/.luarocks/lib64/lua/5.4"
  ],
  "luai -b main.lua -o build/moon": [
   "ok",
   "executable: /home/waterrun/moon/build/moon/moon"
  ],
  "luai -b --file main.lua -o build/moon-onefile": [
   "ok",
   "executable: /home/waterrun/moon/build/moon-onefile"
  ],
  "find build/moon": [
   "moon",
   "moon/.luai",
   "moon/.luai/build",
   "moon/.luai/build/RELINKING.adoc",
   "moon/.luai/build/generate-onefile-payload.lua",
   "moon/.luai/build/launcher.c",
   "moon/.luai/generated-output.txt",
   "moon/.luai/licenses",
   "moon/.luai/licenses/GPL-3.0-or-later.txt",
   "moon/.luai/licenses/LGPL-3.0-or-later.txt",
   "moon/.luai/licenses/Lua-MIT.txt",
   "moon/.luai/manifest.lua",
   "moon/.luai/native",
   "moon/.luai/native/liblua-5.4.so",
   "moon/THIRD_PARTY_NOTICES.md",
   "moon/moon"
  ]
 },
 "secs": {
  "dir": 1.8,
  "onefile": 3.0,
  "websql": 5.5
 },
 "size": {
  "moon": 22472,
  "moon-onefile": 486280,
  "liblua-5.4.so": 287400
 },
 "err": {
  "bad_date": [
   "luainstaller: moon/julian.lua:6: expected YYYY-MM-DD",
   "stack traceback:",
   "\t[C]: in function 'error'",
   "\tluainstaller-bootstrap:210: in function <luainstaller-bootstrap:184>",
   "\t(...tail calls...)",
   "exit code 1"
  ],
  "onefile_exists": [
   "error: InvalidOutputError: Onefile output path already exists: /home/waterrun/moon/build/moon-onefile"
  ],
  "max_deps": [
   "error: DependencyLimitExceededError: Dependency count (3) exceeds limit (2)"
  ],
  "target_os": [
   "error: UnsupportedPlatformError: luainstaller only builds for the native host OS and architecture"
  ],
  "lua_prefix": [
   "error: ToolchainError: Lua prefix does not contain development files for the selected Lua ABI"
  ],
  "not_found": [
   "error: ScriptNotFoundError: Lua script not found: nothere.lua"
  ],
  "module": [
   "error: ModuleNotFoundError: Cannot resolve module 'not.installed' required in /home/waterrun/missing/main.lua",
   "Searched: /home/waterrun/missing, /home/waterrun/missing/src, /home/waterrun/missing/lib, /home/waterrun/missing/lua_modules, /usr/share/lua/5.4, /usr/lib64/lua/5.4, ., /home/waterrun/.luarocks/share/lua/5.4, /home/waterrun/.luarocks/lib64/lua/5.4"
  ],
  "syntax": [
   "error: LuaSyntaxError: Invalid Lua syntax in /home/waterrun/moon/moon/names.lua: /home/waterrun/moon/moon/names.lua:14: <eof> expected near 'this'"
  ],
  "luajit": {
   "cmd": "luajit bin/luai.lua -a ~/moon/main.lua",
   "out": [
    "error: UnsupportedLuaVersionError: luainstaller requires an official Lua 5.1 through 5.5 interpreter"
   ],
   "version": "LuaJIT 2.1.1767980792",
   "runtime": [
    "error: ToolchainError: Runtime discovery interpreter must be official Lua and match the active Lua ABI"
   ]
  }
 },
 "path_start": [
  "2026-10-01  waning gibbous  78% lit"
 ],
 "rebuild": {
  "extra": [
   "error: InvalidOutputError: Generated output contains an unexpected top-level entry"
  ],
  "edited": [
   "error: InvalidOutputError: Generated output no longer matches its ownership marker"
  ],
  "edited_cmd": "echo \"edited\" >> build/moon/THIRD_PARTY_NOTICES.md && luai -b main.lua -o build/moon",
  "foreign": [
   "error: InvalidOutputError: Generated output marker is missing or unreadable"
  ],
  "before": "2eda4a9aa949ff47b13b19e3595fe82cd660430fef0fed55d6daffc687e6dcbe",
  "after": "2eda4a9aa949ff47b13b19e3595fe82cd660430fef0fed55d6daffc687e6dcbe"
 },
 "dyn": {
  "src": [
   "local name = arg[1] or \"sqlite\"",
   "local driver = require(\"drivers.\" .. name)",
   "print(driver.name)"
  ],
  "static": [
   "error: DynamicRequireError: Dynamic require at /home/waterrun/dyn/main.lua:2: require('drivers.' .. ...)",
   "Only static require('name') is supported."
  ],
  "runtime_mysql": [
   "ok",
   "entry: main.lua",
   "scripts: 1",
   "libraries: 0",
   "script[1]: /home/waterrun/dyn/drivers/mysql.lua"
  ],
  "runtime_default": [
   "ok",
   "entry: main.lua",
   "scripts: 1",
   "libraries: 0",
   "script[1]: /home/waterrun/dyn/drivers/sqlite.lua"
  ],
  "manual_cmd": "luai -a main.lua -d manual --include drivers/sqlite.lua --include drivers/mysql.lua",
  "manual": [
   "ok",
   "entry: main.lua",
   "scripts: 2",
   "libraries: 0",
   "script[1]: /home/waterrun/dyn/drivers/sqlite.lua",
   "script[2]: /home/waterrun/dyn/drivers/mysql.lua"
  ],
  "run": [
   "mysql driver",
   "sqlite driver"
  ]
 },
 "native": {
  "src": "local lfs = require(\"lfs\")",
  "analyze": [
   "ok",
   "entry: main.lua",
   "scripts: 0",
   "libraries: 1",
   "library[1]: /usr/lib64/lua/5.4/lfs.so"
  ],
  "trace": "1: native resolved lfs -> /usr/lib64/lua/5.4/lfs.so",
  "warning": "warning: native Lua C modules may require external shared libraries that are not automatically closed over",
  "files": [
   ".luai/native/lfs.so",
   ".luai/native/liblua-5.4.so"
  ],
  "run": [
   "5.1  5.4"
  ],
  "build": [
   "ok",
   "executable: /home/waterrun/list/build/list/list"
  ],
  "find": [
   ".luai/native",
   ".luai/native/lfs.so",
   ".luai/native/liblua-5.4.so"
  ]
 },
 "api": [
  "VERSION\t1.4.0",
  "analyze.ok\ttrue\tscripts\t3\tlibraries\t0",
  "compatibility\tsame OS, same architecture, same ABI, same Lua ABI",
  "host\tlinux\tx86_64\tlua\tLua 5.4",
  "bundle.ok\ttrue\t/home/waterrun/moon/build/api/moon/moon",
  "bad.ok\tfalse\tInvalidOptionsError\tunknown option: colour",
  "dyn.ok\tfalse\tDynamicRequireError",
  "logs\t2\tanalyze\terror"
 ],
 "api_src": [
  "local luainstaller = require(\"luainstaller\")",
  "print(\"VERSION\", luainstaller.VERSION)",
  "",
  "local a = luainstaller.analyze({ entry = \"main.lua\" })",
  "print(\"analyze.ok\", a.ok, \"scripts\", #a.dependencies.scripts, \"libraries\", #a.dependencies.libraries)",
  "",
  "local c = luainstaller.compatibility({ entry = \"main.lua\" })",
  "print(\"compatibility\", c.compatibility.summary)",
  "print(\"host\", c.compatibility.host.os, c.compatibility.host.arch, \"lua\", c.compatibility.lua.version)",
  "",
  "local b = luainstaller.bundle({ entry = \"main.lua\", out = \"build/api/moon\" })",
  "print(\"bundle.ok\", b.ok, b.executable)",
  "",
  "local bad = luainstaller.bundle({ entry = \"main.lua\", out = \"build/api/moon\", colour = \"blue\" })",
  "print(\"bad.ok\", bad.ok, bad.error.type, bad.error.message)",
  "",
  "local e = luainstaller.analyze({ entry = \"/home/waterrun/dyn/main.lua\" })",
  "print(\"dyn.ok\", e.ok, e.error.type)",
  "",
  "local logs = luainstaller.getLogs({ limit = 2 })",
  "print(\"logs\", #logs, logs[1] and logs[1].action, logs[1] and logs[1].level)"
 ],
 "default_out": [
  "ok",
  "executable: /home/waterrun/moon/build/main/main"
 ],
 "logs": [
  "Showing 3 log(s)",
  "  [2026-10-01T09:24:16Z] error   api:analyze Dynamic require at /home/waterrun/dyn/main.lua:2: require('drivers.' .. ...)",
  "Only static require('name') is supported.",
  "  [2026-10-01T09:24:16Z] error   api:bundle unknown option: colour",
  "  [2026-10-01T09:24:07Z] error   api:bundle Lua prefix does not contain development files for the selected Lua ABI"
 ],
 "web": {
  "analyze": [
   "ok",
   "entry: test/firebird_web_sql/server.lua",
   "scripts: 17",
   "libraries: 2",
   "script[1]: /usr/share/lua/5.4/socket.lua",
   "script[2]: /usr/share/lua/5.4/mimetypes/generated.lua",
   "script[3]: /usr/share/lua/5.4/mimetypes/extensions.lua",
   "script[4]: /usr/share/lua/5.4/mimetypes/filenames.lua",
   "script[5]: /usr/share/lua/5.4/mimetypes.lua",
   "script[6]: /usr/share/lua/5.4/pegasus/response.lua",
   "script[7]: /usr/share/lua/5.4/pegasus/request.lua",
   "script[8]: /usr/share/lua/5.4/pegasus/plugins/files.lua",
   "script[9]: /usr/share/lua/5.4/pegasus/log.lua",
   "script[10]: /usr/share/lua/5.4/pegasus/handler.lua",
   "script[11]: /home/waterrun/luainstaller-src/test/firebird_web_sql/logging.lua",
   "script[12]: /usr/share/lua/5.4/pegasus/init.lua",
   "script[13]: /home/waterrun/luainstaller-src/test/firebird_web_sql/config.lua",
   "script[14]: /home/waterrun/luainstaller-src/test/firebird_web_sql/db.lua",
   "script[15]: /home/waterrun/luainstaller-src/test/firebird_web_sql/history.lua",
   "script[16]: /home/waterrun/luainstaller-src/test/firebird_web_sql/security.lua",
   "script[17]: /home/waterrun/luainstaller-src/test/firebird_web_sql/web.lua",
   "library[1]: /usr/lib64/lua/5.4/socket/core.so",
   "library[2]: /usr/lib64/lua/5.4/cjson.so"
  ],
  "scripts": 17,
  "libraries": 2,
  "trace": [
   "1: lua resolved pegasus -> /usr/share/lua/5.4/pegasus/init.lua",
   "2: lua resolved socket -> /usr/share/lua/5.4/socket.lua",
   "3: builtin builtin string",
   "4: builtin builtin math",
   "5: native resolved socket.core -> /usr/lib64/lua/5.4/socket/core.so",
   "6: lua resolved pegasus.handler -> /usr/share/lua/5.4/pegasus/handler.lua",
   "7: lua resolved pegasus.request -> /usr/share/lua/5.4/pegasus/request.lua",
   "8: lua resolved pegasus.response -> /usr/share/lua/5.4/pegasus/response.lua",
   "9: lua resolved mimetypes -> /usr/share/lua/5.4/mimetypes.lua",
   "10: lua resolved mimetypes.extensions -> /usr/share/lua/5.4/mimetypes/extensions.lua",
   "11: lua resolved mimetypes.generated -> /usr/share/lua/5.4/mimetypes/generated.lua",
   "12: lua resolved mimetypes.filenames -> /usr/share/lua/5.4/mimetypes/filenames.lua",
   "13: lua resolved pegasus.response -> /usr/share/lua/5.4/pegasus/response.lua",
   "14: lua resolved pegasus.plugins.files -> /usr/share/lua/5.4/pegasus/plugins/files.lua",
   "15: lua resolved mimetypes -> /usr/share/lua/5.4/mimetypes.lua",
   "16: lua resolved pegasus.log -> /usr/share/lua/5.4/pegasus/log.lua",
   "17: lua resolved logging -> /home/waterrun/luainstaller-src/test/firebird_web_sql/logging.lua",
   "18: lua resolved pegasus.log -> /usr/share/lua/5.4/pegasus/log.lua",
   "19: native resolved cjson -> /usr/lib64/lua/5.4/cjson.so",
   "20: lua resolved config -> /home/waterrun/luainstaller-src/test/firebird_web_sql/config.lua",
   "21: lua resolved db -> /home/waterrun/luainstaller-src/test/firebird_web_sql/db.lua",
   "22: missing optional-missing luasql.firebird",
   "23: lua resolved history -> /home/waterrun/luainstaller-src/test/firebird_web_sql/history.lua",
   "24: lua resolved security -> /home/waterrun/luainstaller-src/test/firebird_web_sql/security.lua",
   "25: missing optional-missing openssl",
   "26: lua resolved web -> /home/waterrun/luainstaller-src/test/firebird_web_sql/web.lua"
  ],
  "build_cmd": "luai -b test/firebird_web_sql/server.lua -o ~/websql",
  "build": [
   "ok",
   "executable: /home/waterrun/websql/websql"
  ],
  "du": "1.6M",
  "clean": {
   "lua -v": [
    "bash: lua: command not found"
   ],
   "./websql/websql &": [
    "[2026-10-01 11:16:11] [WARN ] default token in use; set FIREBIRD_WEB_SQL_TOKEN for real use",
    "[2026-10-01 11:16:11] [INFO ] Firebird Web SQL Shell 2.0.0",
    "[2026-10-01 11:16:11] [INFO ] listen: http://127.0.0.1:9090",
    "[2026-10-01 11:16:11] [INFO ] driver: mock",
    "[2026-10-01 11:16:11] [INFO ] auth: X-Auth-Token",
    "Pegasus is up on 127.0.0.1:9090"
   ],
   "curl -si http://127.0.0.1:9090/ | head -1": [
    "HTTP/1.1 200 OK"
   ]
  },
  "native": [
   "./.luai/native/cjson.so",
   "./.luai/native/core.so",
   "./.luai/native/liblua-5.4.so",
   "./.luai/native/socket"
  ],
  "http": [
   "HTTP/1.1 200 OK",
   "Content-Type: text/html; charset=utf-8",
   "[2026-10-01 09:33:18] [WARN ] default token in use; set FIREBIRD_WEB_SQL_TOKEN for real use",
   "[2026-10-01 09:33:18] [INFO ] Firebird Web SQL Shell 2.0.0",
   "[2026-10-01 09:33:18] [INFO ] listen: http://127.0.0.1:9090"
  ]
 },
 "win": {
  "set LUAI_LUA_PREFIX=C:\\luai-demo\\lua55": [],
  "luai -v": [
   "luai 1.4.0"
  ],
  "luai -a main.lua": [
   "ok",
   "entry: main.lua",
   "scripts: 3",
   "libraries: 0",
   "script[1]: C:/luai-demo/moon/moon/julian.lua",
   "script[2]: C:/luai-demo/moon/moon/phase.lua",
   "script[3]: C:/luai-demo/moon/moon/names.lua"
  ],
  "luai -b main.lua -o build\\moon": [
   "ok",
   "executable: C:/luai-demo/moon/build/moon/moon.exe"
  ],
  "dir /b build\\moon": [
   ".luai",
   "lua55.dll",
   "moon.exe",
   "THIRD_PARTY_NOTICES.md"
  ],
  "build\\moon\\moon.exe 2026-10-01": [
   "2026-10-01  waning gibbous  78% lit"
  ]
 },
 "win_note": "Windows 11 · MSVC 19.51 · Lua 5.5.0",
 "win_sizes": {
  "lua55.dll": 371668,
  "moon.exe": 151552
 },
 "src": {
  "main": [
   "-- moon: print the phase of the Moon for a date.",
   "local phase = require(\"moon.phase\")",
   "local names = require(\"moon.names\")",
   "",
   "local date = arg[1] or os.date(\"!%Y-%m-%d\")",
   "local p = phase.of(date)",
   "",
   "print((\"%s  %s  %d%% lit\"):format(date, names.of(p.angle), p.lit))"
  ],
  "phase": [
   "-- Phase angle and illuminated fraction of the Moon (Meeus, ch. 48, low accuracy).",
   "local julian = require(\"moon.julian\")",
   "",
   "local M = {}",
   "",
   "local rad, sin, cos = math.rad, math.sin, math.cos",
   "",
   "function M.of(date)",
   "    local jd = julian.day(date)",
   "    local T = (jd - 2451545.0) / 36525",
   "",
   "    -- mean elongation, Sun's anomaly, Moon's anomaly (degrees)",
   "    local D  = 297.8501921 + 445267.1114034 * T",
   "    local Ms = 357.5291092 + 35999.0502909 * T",
   "    local Mm = 134.9633964 + 477198.8675055 * T",
   "",
   "    local i = 180 - D",
   "        - 6.289 * sin(rad(Mm))",
   "        + 2.100 * sin(rad(Ms))",
   "        - 1.274 * sin(rad(2 * D - Mm))",
   "        - 0.658 * sin(rad(2 * D))",
   "        - 0.214 * sin(rad(2 * Mm))",
   "        - 0.110 * sin(rad(D))",
   "",
   "    local lit = (1 + cos(rad(i))) / 2",
   "    return {",
   "        angle = (180 - i) % 360,              -- 0 new, 180 full",
   "        lit = math.floor(lit * 100 + 0.5),",
   "    }",
   "end",
   "",
   "return M"
  ],
  "julian": [
   "-- Julian day number of a calendar date at 00:00 UTC.",
   "local M = {}",
   "",
   "function M.day(date)",
   "    local y, m, d = date:match(\"^(%d+)-(%d+)-(%d+)$\")",
   "    assert(y, \"expected YYYY-MM-DD\")",
   "    y, m, d = tonumber(y), tonumber(m), tonumber(d)",
   "    if m <= 2 then",
   "        y, m = y - 1, m + 12",
   "    end",
   "    local a = math.floor(y / 100)",
   "    local b = 2 - a + math.floor(a / 4)",
   "    return math.floor(365.25 * (y + 4716))",
   "        + math.floor(30.6001 * (m + 1)) + d + b - 1524.5",
   "end",
   "",
   "return M"
  ],
  "names": [
   "-- Name of the phase for an elongation angle (0 new, 180 full).",
   "local M = {}",
   "",
   "local list = {",
   "    \"new moon\", \"waxing crescent\", \"first quarter\", \"waxing gibbous\",",
   "    \"full moon\", \"waning gibbous\", \"last quarter\", \"waning crescent\",",
   "}",
   "",
   "function M.of(angle)",
   "    return list[math.floor((angle + 22.5) / 45) % 8 + 1]",
   "end",
   "",
   "return M"
  ]
 },
 "search": [
  "/home/waterrun/moon",
  "/home/waterrun/moon/src",
  "/home/waterrun/moon/lib",
  "/home/waterrun/moon/lua_modules",
  "/usr/share/lua/5.4",
  "/usr/lib64/lua/5.4",
  ".",
  "/home/waterrun/.luarocks/share/lua/5.4",
  "/home/waterrun/.luarocks/lib64/lua/5.4"
 ],
 "manifest": [
  {
   "id": "main.lua",
   "sha": "5bd8b82a4f68c6dee81c00628ddb6ea0f507a6fb3f1e3a7271c981655ba3908e",
   "dest": ".luai/lua/main.lua"
  },
  {
   "id": "moon/julian.lua",
   "sha": "ce92eadc883aa308b7d1c9386615946fc7e65e527b970a7224a043648ec8bf2f",
   "dest": ".luai/lua/moon/julian.lua"
  },
  {
   "id": "moon/names.lua",
   "sha": "b5b8c6bc29f65dc7fee21b488e4ddbb49952c0fe388032142223c7f85867675b",
   "dest": ".luai/lua/moon/names.lua"
  },
  {
   "id": "moon/phase.lua",
   "sha": "ba3040b896a413d395d316c4413415041508286971f7243af3d358210fdf4a09",
   "dest": ".luai/lua/moon/phase.lua"
  }
 ],
 "trace": [
  "1: lua resolved moon.phase -> /home/waterrun/moon/moon/phase.lua",
  "2: lua resolved moon.julian -> /home/waterrun/moon/moon/julian.lua",
  "3: lua resolved moon.names -> /home/waterrun/moon/moon/names.lua"
 ],
 "cc": {
  "probe_native": "gcc -std=c99 -Wall -Wextra -shared -fPIC -I/usr/include native-probe.c -o luai_native_probe.so",
  "probe": "gcc -std=c99 -Wall -Wextra -I/usr/include probe.c -o probe /usr/lib64/liblua-5.4.so -lm -ldl",
  "launcher": "gcc -std=c99 -Wall -Wextra -I/usr/include .luai/build/launcher.c -o moon -Wl,-rpath,$ORIGIN/.luai/native /usr/lib64/liblua-5.4.so -lm -ldl",
  "abi": "gcc -std=c99 -Wall -Wextra -I/usr/include .luai/build/lua-abi-probe.c -o .luai/build/lua-abi-probe -Wl,-rpath,$ORIGIN/.luai/native /usr/lib64/liblua-5.4.so -lm -ldl",
  "staging": "build/.luai-staging-e1fe95f92bfa230c36edaac9-7fd9d48ded1e6b6c81fd3adad75c516248363c5b7a6071f25e91ef9ba6788eca"
 },
 "boot": {
  "size": 6964,
  "lines": 824,
  "array_rows": 581,
  "head": [
   45,
   45,
   32,
   108,
   117,
   97,
   105,
   110,
   115,
   116,
   97,
   108,
   108,
   101,
   114,
   32,
   103,
   101,
   110,
   101,
   114,
   97,
   116,
   101,
   100,
   32,
   98,
   111,
   111,
   116,
   115,
   116,
   114,
   97,
   112,
   10,
   45,
   45,
   32,
   76,
   117,
   97,
   32,
   65,
   66,
   73,
   58,
   32,
   108,
   117,
   97,
   53,
   46,
   52,
   10,
   108,
   111,
   99,
   97,
   108,
   32,
   109,
   111,
   100,
   117,
   108,
   101,
   95,
   114,
   101,
   99,
   111,
   114,
   100,
   115,
   32,
   61,
   32,
   123,
   10,
   32,
   32,
   91,
   49,
   93,
   32,
   61,
   32,
   123,
   10,
   32,
   32,
   32,
   32,
   112,
   97
  ],
  "text": [
   "-- luainstaller generated bootstrap",
   "-- Lua ABI: lua5.4",
   "local module_records = {",
   "  [1] = {",
   "    path = \"moon/julian.lua\",",
   "    source = \"-- Julian day number of a calendar date at 00:00 UTC.\\",
   "local M = {}\\",
   "\\"
  ],
  "insert": "table.insert(searchers, 2, searcher)",
  "modules": [
   "    [\"moon.julian\"] = module_records[1],",
   "    [\"moon.names\"] = module_records[3],",
   "    [\"moon.phase\"] = module_records[2],"
  ],
  "cmain": [
   "L = luaL_newstate();",
   "luaL_openlibs(L);",
   "luai_push_arg(L, argc, argv);",
   "status = luai_load_bootstrap(L);",
   "status = lua_pcall(L, 0, LUA_MULTRET, traceback_index);"
  ],
  "guard": [
   "#if !defined(LUA_VERSION_NUM) || LUA_VERSION_NUM != 504",
   "#error \"luainstaller was generated for a different Lua ABI\""
  ],
  "decl": "static const unsigned char luai_bootstrap[] = {",
  "first_rows": [
   "0x2D, 0x2D, 0x20, 0x6C, 0x75, 0x61, 0x69, 0x6E, 0x73, 0x74, 0x61, 0x6C,",
   "0x6C, 0x65, 0x72, 0x20, 0x67, 0x65, 0x6E, 0x65, 0x72, 0x61, 0x74, 0x65,",
   "0x64, 0x20, 0x62, 0x6F, 0x6F, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x0A,",
   "0x2D, 0x2D, 0x20, 0x4C, 0x75, 0x61, 0x20, 0x41, 0x42, 0x49, 0x3A, 0x20,",
   "0x6C, 0x75, 0x61, 0x35, 0x2E, 0x34, 0x0A, 0x6C, 0x6F, 0x63, 0x61, 0x6C,",
   "0x20, 0x6D, 0x6F, 0x64, 0x75, 0x6C, 0x65, 0x5F, 0x72, 0x65, 0x63, 0x6F,",
   "0x72, 0x64, 0x73, 0x20, 0x3D, 0x20, 0x7B, 0x0A, 0x20, 0x20, 0x5B, 0x31,",
   "0x5D, 0x20, 0x3D, 0x20, 0x7B, 0x0A, 0x20, 0x20, 0x20, 0x20, 0x70, 0x61,"
  ],
  "src": [
   "-- luainstaller generated bootstrap",
   "-- Lua ABI: lua5.4",
   "local module_records = {",
   "  [1] = {",
   "    path = \"moon/julian.lua\",",
   "    source = \"-- Julian day number of a calendar date at 00:00 UTC.\\",
   "local M = {}\\",
   "\\",
   "function M.day(date)\\",
   "    local y, m, d = date:match(\\\"^(%d+)-(%d+)-(%d+)$\\\")\\",
   "    assert(y, \\\"expected YYYY-MM-DD\\\")\\",
   "    y, m, d = tonumber(y), tonumber(m), tonumber(d)\\",
   "    if m <= 2 then\\",
   "        y, m = y - 1, m + 12\\",
   "    end\\",
   "    local a = math.floor(y / 100)\\",
   "    local b = 2 - a + math.floor(a / 4)\\",
   "    return math.floor(365.25 * (y + 4716))\\",
   "        + math.floor(30.6001 * (m + 1)) + d + b - 1524.5\\",
   "end\\",
   "\\",
   "return M\\",
   "\",",
   "  },",
   "  [2] = {",
   "    path = \"moon/phase.lua\",",
   "    source = \"-- Phase angle and illuminated fraction of the Moon (Meeus, ch. 48, low accuracy).\\",
   "local julian = require(\\\"moon.julian\\\")\\",
   "\\",
   "local M = {}\\",
   "\\",
   "local rad, sin, cos = math.rad, math.sin, math.cos\\",
   "\\",
   "function M.of(date)\\",
   "    local jd = julian.day(date)\\",
   "    local T = (jd - 2451545.0) / 36525\\",
   "\\",
   "    -- mean elongation, Sun's anomaly, Moon's anomaly (degrees)\\",
   "    local D  = 297.8501921 + 445267.1114034 * T\\",
   "    local Ms = 357.5291092 + 35999.0502909 * T\\",
   "    local Mm = 134.9633964 + 477198.8675055 * T\\",
   "\\",
   "    local i = 180 - D\\",
   "        - 6.289 * sin(rad(Mm))\\",
   "        + 2.100 * sin(rad(Ms))\\",
   "        - 1.274 * sin(rad(2 * D - Mm))\\",
   "        - 0.658 * sin(rad(2 * D))\\",
   "        - 0.214 * sin(rad(2 * Mm))\\",
   "        - 0.110 * sin(rad(D))\\",
   "\\",
   "    local lit = (1 + cos(rad(i))) / 2\\",
   "    return {\\",
   "        angle = (180 - i) % 360,              -- 0 new, 180 full\\",
   "        lit = math.floor(lit * 100 + 0.5),\\",
   "    }\\",
   "end\\",
   "\\",
   "return M\\",
   "\",",
   "  },",
   "  [3] = {",
   "    path = \"moon/names.lua\",",
   "    source = \"-- Name of the phase for an elongation angle (0 new, 180 full).\\",
   "local M = {}\\",
   "\\",
   "local list = {\\",
   "    \\\"new moon\\\", \\\"waxing crescent\\\", \\\"first quarter\\\", \\\"waxing gibbous\\\",\\",
   "    \\\"full moon\\\", \\\"waning gibbous\\\", \\\"last quarter\\\", \\\"waning crescent\\\",\\",
   "}\\",
   "\\",
   "function M.of(angle)\\",
   "    return list[math.floor((angle + 22.5) / 45) % 8 + 1]\\",
   "end\\",
   "\\",
   "return M\\",
   "\",",
   "  },",
   "}",
   "local payload = {",
   "  entry = {",
   "    id = \"__entry__\",",
   "    path = \"main.lua\",",
   "    source = \"-- moon: print the phase of the Moon for a date.\\",
   "local phase = require(\\\"moon.phase\\\")\\",
   "local names = require(\\\"moon.names\\\")\\",
   "\\",
   "local date = arg[1] or os.date(\\\"!%Y-%m-%d\\\")\\",
   "local p = phase.of(date)\\",
   "\\",
   "print((\\\"%s  %s  %d%% lit\\\"):format(date, names.of(p.angle), p.lit))\\",
   "\",",
   "  },",
   "  modules = {",
   "    [\"moon.julian\"] = module_records[1],",
   "    [\"moon.names\"] = module_records[3],",
   "    [\"moon.phase\"] = module_records[2],",
   "  },",
   "}",
   "local function pathDirname(path)",
   "  path = tostring(path or \"\"):gsub(\"\\\\\", \"/\")",
   "  return path:match(\"^(.*)/[^/]+$\") or \".\"",
   "end",
   "",
   "local function joinPath(left, right)",
   "  left = tostring(left or \"\")",
   "  right = tostring(right or \"\")",
   "  if right:sub(1, 1) == \"/\" or right:match(\"^%a:/\") then return right end",
   "  if left == \"\" or left == \".\" then return right end",
   "  return left:gsub(\"/+$\", \"\") .. \"/\" .. right",
   "end",
   "",
   "local function configureNativePath(native_dir, launcher_path)",
   "  if not native_dir or native_dir == \"\" then return end",
   "  local resolved = joinPath(pathDirname(launcher_path), native_dir)",
   "  local patterns = table.concat({",
   "    resolved .. \"/?.so\",",
   "    resolved .. \"/?/init.so\",",
   "    resolved .. \"/?.dylib\",",
   "    resolved .. \"/?/init.dylib\",",
   "    resolved .. \"/?.dll\",",
   "    resolved .. \"/?/init.dll\",",
   "  }, \";\")",
   "  package.cpath = patterns .. \";\" .. package.cpath",
   "end",
   "",
   "local function stripSource(source)",
   "  source = tostring(source or \"\")",
   "  if source:sub(1, 3) == \"\\239\\187\\191\" then source = source:sub(4) end",
   "  if source:sub(1, 2) == \"#!\" then",
   "    local newline_start, newline_end = source:find(\"\\r\\n\", 1, true)",
   "    if not newline_start then newline_start, newline_end = source:find(\"[\\r\\n]\") end",
   "    if newline_start then source = \"\\n\" .. source:sub(newline_end + 1) else source = \"\" end",
   "  end",
   "  return source",
   "end",
   "",
   "local function loaderTable()",
   "  return package.searchers or package.loaders",
   "end",
   "",
   "local unpackValues = table.unpack or unpack",
   "",
   "local function packValues(...)",
   "  return { n = select(\"#\", ...), ... }",
   "end",
   "",
   "local function loadText(source, chunk_name)",
   "  if type(source) ~= \"string\" then return nil, \"source must be a string\" end",
   "  if source:byte(1) == 27 then return nil, \"binary chunks are not accepted\" end",
   "  if _VERSION == \"Lua 5.1\" then return loadstring(source, chunk_name) end",
   "  return load(source, chunk_name, \"t\")",
   "end",
   "",
   "local function loadPayloadSource(record, chunk_name)",
   "  local loader, err = loadText(stripSource(record.source or \"\"), chunk_name or (\"@\" .. tostring(record.path or \"bundle\")))",
   "  if not loader then error(err) end",
   "  return loader",
   "end",
   "",
   "local function restoreLoadedModules(loaded, previous_modules)",
   "  for name, previous in pairs(previous_modules) do",
   "    if previous.present then rawset(loaded, name, previous.value)",
   "    else rawset(loaded, name, nil) end",
   "  end",
   "end",
   "",
   "local function install(payload)",
   "  local modules = payload.modules or {}",
   "  local searchers = loaderTable()",
   "  local searcher",
   "  searcher = function(module_name)",
   "    local record = modules[module_name]",
   "    if not record then return \"\\n\\tno bundled module '\" .. tostring(module_name) .. \"'\" end",
   "    return loadPayloadSource(record, \"@\" .. tostring(record.path or module_name)), record.path",
   "  end",
   "  table.insert(searchers, 2, searcher)",
   "  return function()",
   "    for i = #searchers, 1, -1 do",
   "      if searchers[i] == searcher then table.remove(searchers, i); break end",
   "    end",
   "  end",
   "end",
   "",
   "local function run(payload, run_args, application_arg0)",
   "  local loaded = package.loaded",
   "  local previous_modules = {}",
   "  for name in pairs(payload.modules or {}) do",
   "    local value = rawget(loaded, name)",
   "    previous_modules[name] = { present = value ~= nil, value = value }",
   "    rawset(loaded, name, nil)",
   "  end",
   "  local install_ok, uninstall = pcall(install, payload)",
   "  if not install_ok then",
   "    restoreLoadedModules(loaded, previous_modules)",
   "    error(uninstall, 0)",
   "  end",
   "  local old_arg = _G.arg",
   "  local entry = payload.entry",
   "  local runtime_arg = { [0] = application_arg0",
   "      or (type(old_arg) == \"table\" and old_arg[0])",
   "      or entry.path or entry.id or \"__entry__\" }",
   "  for i = 1, #(run_args or {}) do runtime_arg[i] = run_args[i] end",
   "  _G.arg = runtime_arg",
   "  local results = packValues(pcall(function()",
   "    return loadPayloadSource(entry, \"@\" .. tostring(entry.path or entry.id or \"__entry__\"))()",
   "  end))",
   "  _G.arg = old_arg",
   "  local uninstall_ok, uninstall_err = pcall(uninstall)",
   "  restoreLoadedModules(loaded, previous_modules)",
   "  if not results[1] then error(results[2], 0) end",
   "  if not uninstall_ok then error(uninstall_err, 0) end",
   "  return unpackValues(results, 2, results.n)",
   "end",
   "",
   "local application_arg0 = arg and arg[0] or \"\"",
   "local launcher_path = rawget(_G, \"__luai_executable_path\") or application_arg0",
   "rawset(_G, \"__luai_executable_path\", nil)",
   "configureNativePath(\".luai/native\", launcher_path)",
   "local run_args = {}",
   "if arg then for i = 1, #arg do run_args[i] = arg[i] end end",
   "return run(payload, run_args, application_arg0)"
  ]
 },
 "launcher": {
  "lines": 824,
  "decl_line": 13,
  "size_line": 596,
  "error_line": 635,
  "main_line": 786,
  "load_line": 767,
  "main": [
   "int main(int argc, char **argv) {",
   "    lua_State *L;",
   "    int status;",
   "    int traceback_index;",
   "",
   "    L = luaL_newstate();",
   "    if (L == NULL) {",
   "        fputs(\"luainstaller: cannot create Lua state\\n\", stderr);",
   "        return 70;",
   "    }",
   "",
   "    luaL_openlibs(L);",
   "    if (!luai_runtime_matches(L)) {",
   "        fputs(\"luainstaller: linked Lua runtime is not Lua 5.4\\n\", stderr);",
   "        lua_close(L);",
   "        return 70;",
   "    }",
   "    luai_push_arg(L, argc, argv);",
   "",
   "    lua_pushcfunction(L, luai_traceback);",
   "    traceback_index = lua_gettop(L);",
   "",
   "    status = luai_load_bootstrap(L);",
   "    if (status == LUA_OK) {",
   "        status = lua_pcall(L, 0, LUA_MULTRET, traceback_index);",
   "    }",
   "",
   "    if (status != LUA_OK) {",
   "        const char *message = lua_tostring(L, -1);",
   "        fprintf(stderr, \"luainstaller: %s\\n\", message ? message : \"unknown launcher error\");",
   "        lua_close(L);",
   "        return 1;",
   "    }",
   "",
   "    lua_close(L);",
   "    return 0;",
   "}"
  ],
  "load": [
   "static int luai_load_bootstrap(lua_State *L) {",
   "#if LUA_VERSION_NUM == 501",
   "    if (luai_bootstrap_size > 0 && luai_bootstrap[0] == 0x1b) return LUA_ERRSYNTAX;",
   "    return luaL_loadbuffer(L, (const char *)luai_bootstrap, luai_bootstrap_size, \"@luainstaller-bootstrap\");",
   "#else",
   "    return luaL_loadbufferx(L, (const char *)luai_bootstrap, luai_bootstrap_size, \"@luainstaller-bootstrap\", \"t\");",
   "#endif",
   "}"
  ],
  "matches": [
   "static int luai_runtime_matches(lua_State *L) {",
   "    const char *version;",
   "    int matches;",
   "    lua_getglobal(L, \"_VERSION\");",
   "    version = lua_tostring(L, -1);",
   "    matches = version != NULL && strcmp(version, \"Lua 5.4\") == 0;",
   "    lua_pop(L, 1);",
   "    return matches;",
   "}"
  ],
  "last_rows": [
   "0x70, 0x70, 0x6C, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6F, 0x6E, 0x5F, 0x61,",
   "0x72, 0x67, 0x30, 0x29,"
  ],
  "lens": [
   32,
   0,
   14,
   0,
   31,
   0,
   25,
   0,
   6,
   0,
   19,
   0,
   47,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   75,
   27,
   2,
   65,
   0,
   2,
   49,
   3,
   0,
   14,
   31,
   25,
   6,
   0,
   18,
   19,
   19,
   0,
   13,
   20,
   27,
   6,
   14,
   27,
   6,
   20,
   24,
   24,
   19,
   52,
   22,
   23,
   19,
   5,
   19,
   6,
   0,
   16,
   20,
   19,
   0,
   55,
   59,
   6,
   0,
   14,
   16,
   6,
   0,
   41,
   45,
   26,
   82,
   21,
   9,
   51,
   5,
   26,
   30,
   30,
   22,
   35,
   17,
   5,
   37,
   33,
   22,
   35,
   17,
   5,
   31,
   26,
   22,
   5,
   37,
   6,
   13,
   1,
   0,
   14,
   74,
   18,
   33,
   27,
   53,
   35,
   13,
   1,
   0,
   84,
   24,
   78,
   47,
   51,
   1,
   0,
   85,
   23,
   23,
   49,
   84,
   28,
   34,
   20,
   14,
   52,
   92,
   29,
   19,
   36,
   74,
   63,
   24,
   16,
   70,
   67,
   9,
   60,
   77,
   30,
   31,
   5,
   14,
   1,
   6,
   0,
   79,
   13,
   15,
   66,
   61,
   13,
   5,
   22,
   19,
   42,
   57,
   64,
   52,
   65,
   27,
   48,
   68,
   48,
   67,
   55,
   27,
   17,
   5,
   6,
   59,
   6,
   1,
   0,
   64,
   26,
   66,
   39,
   10,
   74,
   37,
   5,
   51,
   28,
   26,
   32,
   35,
   30,
   5,
   28,
   39,
   47,
   1,
   0,
   46,
   26,
   83,
   108,
   5,
   114,
   6,
   1,
   0,
   47,
   24,
   16,
   33,
   34,
   65,
   18,
   19,
   1,
   0,
   33,
   17,
   15,
   24,
   0,
   24,
   20,
   65,
   18,
   5,
   0,
   21,
   35,
   75,
   21,
   18,
   5,
   33,
   0,
   41,
   36,
   0,
   36,
   27,
   63,
   5,
   0,
   27,
   50,
   92,
   21,
   17,
   5,
   0,
   17,
   13,
   1,
   0,
   0
  ]
 },
 "bundle_files": [
  {
   "path": ".luai/native/liblua-5.4.so",
   "size": 287400
  },
  {
   "path": ".luai/build/launcher.c",
   "size": 50934
  },
  {
   "path": ".luai/licenses/GPL-3.0-or-later.txt",
   "size": 35149
  },
  {
   "path": "moon",
   "size": 22472
  },
  {
   "path": ".luai/licenses/LGPL-3.0-or-later.txt",
   "size": 7652
  },
  {
   "path": ".luai/build/generate-onefile-payload.lua",
   "size": 6627
  },
  {
   "path": ".luai/manifest.lua",
   "size": 3966
  },
  {
   "path": ".luai/build/RELINKING.adoc",
   "size": 3611
  },
  {
   "path": "THIRD_PARTY_NOTICES.md",
   "size": 2006
  },
  {
   "path": ".luai/generated-output.txt",
   "size": 1102
  },
  {
   "path": ".luai/licenses/Lua-MIT.txt",
   "size": 1068
  }
 ],
 "srcchange": {
  "cmd": "LUAI_CC=/opt/edit/gcc luai -b main.lua -o build/moon",
  "err": [
   "error: SourceChangedError: Source changed during build: /home/waterrun/moon/moon/names.lua"
  ],
  "before": "b5b8c6bc29f65dc7fee21b488e4ddbb49952c0fe388032142223c7f85867675b",
  "after": "e6f74866fe164b0fdcbaa6427c9af52f09d6a82690ff12f20509714bd9b37b4e",
  "built": "2eda4a9aa949ff47b13b19e3595fe82cd660430fef0fed55d6daffc687e6dcbe",
  "kept": "2eda4a9aa949ff47b13b19e3595fe82cd660430fef0fed55d6daffc687e6dcbe",
  "ls": [
   ".",
   "..",
   "moon"
  ],
  "rebuilt": "d4395f7938cd653333a9f4af23fdd5efac82f80793577df25823170bdd9e93cb"
 },
 "abi_probe": [
  "lua_getglobal(state, \"_VERSION\");",
  "version = lua_tostring(state, -1);",
  "matches = version != NULL && strcmp(version, \"Lua 5.4\") == 0;",
  "return matches ? 0 : 42;"
 ],
 "privacy": [
  "0",
  "0"
 ],
 "exe": {
  "size": 22472,
  "b64": "f0VMRgIBAQAAAAAAAAAAAAIAPgABAAAAMAVAAAAAAABAAAAAAAAAAMhPAAAAAAAAAAAAAEAAOAANAEAAIAAfAAYAAAAEAAAAQAAAAAAAAABAAEAAAAAAAEAAQAAAAAAA2AIAAAAAAADYAgAAAAAAAAgAAAAAAAAAAwAAAAQAAAAAEAAAAAAAAAAQQAAAAAAAABBAAAAAAAAcAAAAAAAAABwAAAAAAAAAAQAAAAAAAAABAAAABQAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAI0NAAAAAAAAjQ0AAAAAAAAAEAAAAAAAAAEAAAAEAAAAABAAAAAAAAAAEEAAAAAAAAAQQAAAAAAAeCcAAAAAAAB4JwAAAAAAAAAQAAAAAAAAAQAAAAYAAADIPQAAAAAAAMhNQAAAAAAAyE1AAAAAAAAcAwAAAAAAAEgDAAAAAAAAABAAAAAAAAACAAAABgAAANg9AAAAAAAA2E1AAAAAAADYTUAAAAAAAAACAAAAAAAAAAIAAAAAAAAIAAAAAAAAAAQAAAAEAAAAGAMAAAAAAAAYA0AAAAAAABgDQAAAAAAAJAAAAAAAAAAkAAAAAAAAAAQAAAAAAAAABAAAAAQAAAAYNwAAAAAAABg3QAAAAAAAGDdAAAAAAABAAAAAAAAAAEAAAAAAAAAACAAAAAAAAAAEAAAABAAAAFg3AAAAAAAAWDdAAAAAAABYN0AAAAAAACAAAAAAAAAAIAAAAAAAAAAEAAAAAAAAAFPldGQEAAAAGDcAAAAAAAAYN0AAAAAAABg3QAAAAAAAQAAAAAAAAABAAAAAAAAAAAgAAAAAAAAAUOV0ZAQAAAAcNQAAAAAAABw1QAAAAAAAHDVAAAAAAABsAAAAAAAAAGwAAAAAAAAABAAAAAAAAABR5XRkBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAFLldGQEAAAAyD0AAAAAAADITUAAAAAAAMhNQAAAAAAAOAIAAAAAAAA4AgAAAAAAAAEAAAAAAAAABAAAABQAAAADAAAAR05VAHCT4CsskbSqb82Coe6PWr5+Uc+U8w8e+kiD7AhIiwWVTAAASIXAdAL/0EiDxAjDAAAAAAAAAAAA/zWKTAAA/yWMTAAADx9AAP8likwAAGgAAAAA6eD/////JYJMAABoAQAAAOnQ/////yV6TAAAaAIAAADpwP////8lckwAAGgDAAAA6bD/////JWpMAABoBAAAAOmg/////yViTAAAaAUAAADpkP////8lWkwAAGgGAAAA6YD/////JVJMAABoBwAAAOlw/////yVKTAAAaAgAAADpYP////8lQkwAAGgJAAAA6VD/////JTpMAABoCgAAAOlA/////yUyTAAAaAsAAADpMP////8lKkwAAGgMAAAA6SD/////JSJMAABoDQAAAOkQ/////yUaTAAAaA4AAADpAP////8lEkwAAGgPAAAA6fD+////JQpMAABoEAAAAOng/v///yUCTAAAaBEAAADp0P7///8l+ksAAGgSAAAA6cD+////JfJLAABoEwAAAOmw/v///yXqSwAAaBQAAADpoP7///8l4ksAAGgVAAAA6ZD+////JdpLAABoFgAAAOmA/v///yXSSwAAaBcAAADpcP7///8lyksAAGgYAAAA6WD+////JcJLAABoGQAAAOlQ/v///yW6SwAAaBoAAADpQP7///8lsksAAGgbAAAA6TD+///zDx76Me1JidFeSIniSIPk8FBURTHAMclIx8fuC0AA/xWDSgAA9GYuDx+EAAAAAADzDx76w2YuDx+EAAAAAACQuOhQQABIPehQQAB0E7gAAAAASIXAdAm/6FBAAP/gZpDDDx9AAGZmLg8fhAAAAAAAvuhQQABIge7oUEAASInwSMHuP0jB+ANIAcZI0f50EbgAAAAASIXAdAe/6FBAAP/gww8fQABmZi4PH4QAAAAAAPMPHvqAPR1LAAAAdRNVSInl6Hr////GBQtLAAABXcOQww8fQABmZi4PH4QAAAAAAPMPHvrrilVIieVIg+wgSIl96EiLRei6AAAAAL4BAAAASInH6Mj9//9IiUX4SIN9+AB1P0iLRei6ADRAAL4BAAAASInH6Ff9//+FwHQdSItF6L7/////SInH6IL+//+D+AR1B7gBAAAA6yZIx0X4EDRAAEiLVfhIi3XoSItF6LkBAAAASInH6AX9//+4AQAAAMnDVUiJ5UiD7DBIiX3oSIl14EiJVdhIg33YAHUHuP/////rSEiLRdhIicfoUP3//0iJRfhIg334AHQKSItF+Eg7ReByB7j/////6yBIi0X4SI1QAUiLTdhIi0XoSInOSInH6Ln9//+4AAAAAMnDVUiJ5UiB7CAQAABIib347///SIm18O///0iJlejv//9Ig73o7///AHQeSI2VAPD//0iLhejv//9IidZIicfoX/3//0iFwHUHuP/////rP0iNhQDw//++AQAAAEiJx+hv/f//hcB0B7j/////6yBIjZUA8P//SIuN8O///0iLhfjv//9Iic5IicfoBv///8nDVUiJ5UiB7FAQAABIib3I7///SIm1wO///0iJlbjv//9Ig7247///AHQOSIuFuO///w+2AITAdQq4/////+l5AQAASIuFuO///74vAAAASInH6Dz8//9IhcB0JUiLlbjv//9Ii43A7///SIuFyO///0iJzkiJx+j1/v//6TsBAAC/LzRAAOhI+///SIlF4EiDfeAAdQq4/////+kcAQAASItF4EiJRfhIi0X4vjoAAABIicfo2vv//0iJRdhIg33YAHQOSItF2EgrRfhIiUXw6xBIi0X4SInH6KX7//9IiUXwSIN98AB1LUiLlbjv//9IjYXQ7///SInRujQ0QAC+ABAAAEiJx7gAAAAA6JL7//+JRezrTUiBffD9DwAAdgnHRez/////6zpIi0XwicZIi4247///SItV+EiNhdDv//9JiclJidCJ8bo5NEAAvgAQAABIice4AAAAAOhD+///iUXsg33sAH41i0XsPf8PAAB3K0iNldDv//9Ii43A7///SIuFyO///0iJzkiJx+je/f//hcB1B7gAAAAA6x5Ig33YAHQRSItF2EiDwAFIiUX46fL+//+QuP/////Jw1VIieVIg+wwSIl96EiJdeBIiVXYSItF4EiNUP9Ii0XoSInGv0E0QADoWPr//0iJRfhIg334AHgmSItF4EiD6AFIi1X4SDnCcxVIi1X4SItF6EgB0MYAALgAAAAA6xdIi1XYSItN4EiLRehIic5Iicfozv3//8nDVUiJ5UiB7EAQAABIib3Y7///ibXU7///SImVyO///4O91O///wB+H0iLhcjv//9IiwBIhcB0EEiLhcjv//9IiwBIiUX46whIx0X4UDRAAEiLRfhIiUXwSItV+EiNheDv//++ABAAAEiJx+ga////hcB1C0iNheDv//9IiUXwi4XU7///ugEAAACFwA9Owo1I/0iLhdjv//+6AQAAAInOSInH6Jf5//9Ii1X4SIuF2O///0iJ1kiJx+iB+v//SIuF2O///7oAAAAAvv7///9Iicfo+Pn//8dF7AEAAADrSotF7EiYSI0UxQAAAABIi4XI7///SAHQSIsQSIuF2O///0iJ1kiJx+gz+v//i0XsSGPQSIuF2O///77+////SInH6Kn5//+DRewBi0XsO4XU7///fKtIi4XY7///vlE0QABIicfoRvn//0iLVfBIi4XY7///SInWSInH6OD5//9Ii4XY7///vlU0QABIicfoHPn//5DJw1VIieVIg+wQSIl9+Lo0GwAASItF+EG4bDRAALluNEAAvsAYQABIicfoXPj//8nDVUiJ5UiD7CBIiX3oSItF6L6GNEAASInH6D35//9Ii0XougAAAAC+/////0iJx+hX+P//SIlF+EiDffgAdBxIi0X4vo80QABIicfoq/j//4XAdQe4AQAAAOsFuAAAAACJRfRIi0Xovv7///9Iicfop/f//4tF9MnDVUiJ5UiD7DCJfdxIiXXQ6H74//9IiUXwSIN98AB1KEiLBexEAABIicG6JgAAAL4BAAAAv5g0QADo1fj//7hGAAAA6UYBAABIi0XwSInH6A/4//9Ii0XwSInH6Cn///+FwHU0SIsFqEQAAEiJwbowAAAAvgEAAAC/wDRAAOiR+P//SItF8EiJx+h19///uEYAAADp9gAAAEiLVdCLTdxIi0Xwic5IicfoOP3//0iLRfC6AAAAAL4WBkAASInH6BD3//9Ii0XwSInH6MT2//+JRexIi0XwSInH6Hz+//+JRfyDffwAdSqLVexIi0XwQbkAAAAAQbgAAAAAidG6/////74AAAAASInH6CX4//+JRfyDffwAdGZIi0XwugAAAAC+/////0iJx+jm9v//SIlF4EiDfeAAD5XAD7bAg+ABhMB0BkiLReDrBbjxNEAASIsNvkMAAEiJwr4INUAASInPuAAAAADoOff//0iLRfBIicfojfb//7gBAAAA6xFIi0XwSInH6Hr2//+4AAAAAMnDAAAA8w8e+kiD7AhIg8QIwwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC9saWI2NC9sZC1saW51eC14ODYtNjQuc28uMgAAAAAAAgAAAB8AAAABAAAABgAAAAABAAAAAAACAAAAAB8AAAA58oscAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4BAAASAAAAAAAAAAAAAAAAAAAAAAAAALAAAAASAAAAAAAAAAAAAAAAAAAAAAAAABAAAAASAAAAAAAAAAAAAAAAAAAAAAAAABYBAAASAAAAAAAAAAAAAAAAAAAAAAAAALsAAAASAAAAAAAAAAAAAAAAAAAAAAAAAKIAAAASAAAAAAAAAAAAAAAAAAAAAAAAAFEAAAASAAAAAAAAAAAAAAAAAAAAAAAAAIYAAAASAAAAAAAAAAAAAAAAAAAAAAAAAA0BAAASAAAAAAAAAAAAAAAAAAAAAAAAAHwAAAASAAAAAAAAAAAAAAAAAAAAAAAAAMoAAAASAAAAAAAAAAAAAAAAAAAAAAAAADgAAAASAAAAAAAAAAAAAAAAAAAAAAAAAAYBAAASAAAAAAAAAAAAAAAAAAAAAAAAADcBAAASAAAAAAAAAAAAAAAAAAAAAAAAAPQAAAASAAAAAAAAAAAAAAAAAAAAAAAAANgAAAASAAAAAAAAAAAAAAAAAAAAAAAAACoAAAASAAAAAAAAAAAAAAAAAAAAAAAAAFoBAAASAAAAAAAAAAAAAAAAAAAAAAAAAGIAAAASAAAAAAAAAAAAAAAAAAAAAAAAAC8BAAASAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAASAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAP0AAAASAAAAAAAAAAAAAAAAAAAAAAAAAEwBAAASAAAAAAAAAAAAAAAAAAAAAAAAAOYAAAASAAAAAAAAAAAAAAAAAAAAAAAAAEUBAAASAAAAAAAAAAAAAAAAAAAAAAAAAEgAAAASAAAAAAAAAAAAAAAAAAAAAAAAAFMBAAASAAAAAAAAAAAAAAAAAAAAAAAAABsAAAASAAAAAAAAAAAAAAAAAAAAAAAAAJcAAAASAAAAAAAAAAAAAAAAAAAAAAAAACgBAAARABkAAFFAAAAAAAAIAAAAAAAAAABfX2dtb25fc3RhcnRfXwBsdWFfc2V0dG9wAGx1YV9wdXNoc3RyaW5nAGx1YV9zZXRnbG9iYWwAbHVhX2NyZWF0ZXRhYmxlAGx1YV90eXBlAGx1YV9wdXNoY2Nsb3N1cmUAbHVhTF9uZXdzdGF0ZQBsdWFfcmF3c2V0aQBsdWFfY2xvc2UAbHVhTF9sb2FkYnVmZmVyeABsdWFfcGNhbGxrAGx1YUxfY2FsbG1ldGEAbHVhX2dldHRvcABsdWFMX3RyYWNlYmFjawBsdWFfdG9sc3RyaW5nAGx1YUxfb3BlbmxpYnMAbHVhX2dldGdsb2JhbABzbnByaW50ZgByZWFscGF0aABzdHJsZW4AcmVhZGxpbmsAX19saWJjX3N0YXJ0X21haW4Ac3RkZXJyAGZwcmludGYAc3RyY2hyAGdldGVudgBhY2Nlc3MAbWVtY3B5AGZ3cml0ZQBzdHJjbXAAbGlibHVhLTUuNC5zbwBsaWJtLnNvLjYAbGliYy5zby42AEdMSUJDXzIuMTQAR0xJQkNfMi4zAEdMSUJDXzIuMzQAR0xJQkNfMi4yLjUAJE9SSUdJTi8ubHVhaS9uYXRpdmUAAAACAAAAAAADAAAAAAAAAAAAAgAAAAAAAAACAAIAAgAAAAAAAgAAAAIAAAAAAAQABQAAAAIAAAACAAAAAAACAAAAAAABAAQAeQEAABAAAAAAAAAAlJGWBgAABQCDAQAAEAAAABNpaQ0AAAQAjgEAABAAAAC0kZYGAAADAJgBAAAQAAAAdRppCQAAAgCjAQAAAAAAANhPQAAAAAAABgAAAAQAAAAAAAAAAAAAAOBPQAAAAAAABgAAABYAAAAAAAAAAAAAAABRQAAAAAAABQAAAB8AAAAAAAAAAAAAAABQQAAAAAAABwAAAAEAAAAAAAAAAAAAAAhQQAAAAAAABwAAAAIAAAAAAAAAAAAAABBQQAAAAAAABwAAAAMAAAAAAAAAAAAAABhQQAAAAAAABwAAAAUAAAAAAAAAAAAAACBQQAAAAAAABwAAAAYAAAAAAAAAAAAAAChQQAAAAAAABwAAAAcAAAAAAAAAAAAAADBQQAAAAAAABwAAAAgAAAAAAAAAAAAAADhQQAAAAAAABwAAAAkAAAAAAAAAAAAAAEBQQAAAAAAABwAAAAoAAAAAAAAAAAAAAEhQQAAAAAAABwAAAAsAAAAAAAAAAAAAAFBQQAAAAAAABwAAAAwAAAAAAAAAAAAAAFhQQAAAAAAABwAAAA0AAAAAAAAAAAAAAGBQQAAAAAAABwAAAA4AAAAAAAAAAAAAAGhQQAAAAAAABwAAAA8AAAAAAAAAAAAAAHBQQAAAAAAABwAAABAAAAAAAAAAAAAAAHhQQAAAAAAABwAAABEAAAAAAAAAAAAAAIBQQAAAAAAABwAAABIAAAAAAAAAAAAAAIhQQAAAAAAABwAAABMAAAAAAAAAAAAAAJBQQAAAAAAABwAAABQAAAAAAAAAAAAAAJhQQAAAAAAABwAAABUAAAAAAAAAAAAAAKBQQAAAAAAABwAAABcAAAAAAAAAAAAAAKhQQAAAAAAABwAAABgAAAAAAAAAAAAAALBQQAAAAAAABwAAABkAAAAAAAAAAAAAALhQQAAAAAAABwAAABoAAAAAAAAAAAAAAMBQQAAAAAAABwAAABsAAAAAAAAAAAAAAMhQQAAAAAAABwAAABwAAAAAAAAAAAAAANBQQAAAAAAABwAAAB0AAAAAAAAAAAAAANhQQAAAAAAABwAAAB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALS0gbHVhaW5zdGFsbGVyIGdlbmVyYXRlZCBib290c3RyYXAKLS0gTHVhIEFCSTogbHVhNS40CmxvY2FsIG1vZHVsZV9yZWNvcmRzID0gewogIFsxXSA9IHsKICAgIHBhdGggPSAibW9vbi9qdWxpYW4ubHVhIiwKICAgIHNvdXJjZSA9ICItLSBKdWxpYW4gZGF5IG51bWJlciBvZiBhIGNhbGVuZGFyIGRhdGUgYXQgMDA6MDAgVVRDLlwKbG9jYWwgTSA9IHt9XApcCmZ1bmN0aW9uIE0uZGF5KGRhdGUpXAogICAgbG9jYWwgeSwgbSwgZCA9IGRhdGU6bWF0Y2goXCJeKCVkKyktKCVkKyktKCVkKykkXCIpXAogICAgYXNzZXJ0KHksIFwiZXhwZWN0ZWQgWVlZWS1NTS1ERFwiKVwKICAgIHksIG0sIGQgPSB0b251bWJlcih5KSwgdG9udW1iZXIobSksIHRvbnVtYmVyKGQpXAogICAgaWYgbSA8PSAyIHRoZW5cCiAgICAgICAgeSwgbSA9IHkgLSAxLCBtICsgMTJcCiAgICBlbmRcCiAgICBsb2NhbCBhID0gbWF0aC5mbG9vcih5IC8gMTAwKVwKICAgIGxvY2FsIGIgPSAyIC0gYSArIG1hdGguZmxvb3IoYSAvIDQpXAogICAgcmV0dXJuIG1hdGguZmxvb3IoMzY1LjI1ICogKHkgKyA0NzE2KSlcCiAgICAgICAgKyBtYXRoLmZsb29yKDMwLjYwMDEgKiAobSArIDEpKSArIGQgKyBiIC0gMTUyNC41XAplbmRcClwKcmV0dXJuIE1cCiIsCiAgfSwKICBbMl0gPSB7CiAgICBwYXRoID0gIm1vb24vcGhhc2UubHVhIiwKICAgIHNvdXJjZSA9ICItLSBQaGFzZSBhbmdsZSBhbmQgaWxsdW1pbmF0ZWQgZnJhY3Rpb24gb2YgdGhlIE1vb24gKE1lZXVzLCBjaC4gNDgsIGxvdyBhY2N1cmFjeSkuXApsb2NhbCBqdWxpYW4gPSByZXF1aXJlKFwibW9vbi5qdWxpYW5cIilcClwKbG9jYWwgTSA9IHt9XApcCmxvY2FsIHJhZCwgc2luLCBjb3MgPSBtYXRoLnJhZCwgbWF0aC5zaW4sIG1hdGguY29zXApcCmZ1bmN0aW9uIE0ub2YoZGF0ZSlcCiAgICBsb2NhbCBqZCA9IGp1bGlhbi5kYXkoZGF0ZSlcCiAgICBsb2NhbCBUID0gKGpkIC0gMjQ1MTU0NS4wKSAvIDM2NTI1XApcCiAgICAtLSBtZWFuIGVsb25nYXRpb24sIFN1bidzIGFub21hbHksIE1vb24ncyBhbm9tYWx5IChkZWdyZWVzKVwKICAgIGxvY2FsIEQgID0gMjk3Ljg1MDE5MjEgKyA0NDUyNjcuMTExNDAzNCAqIFRcCiAgICBsb2NhbCBNcyA9IDM1Ny41MjkxMDkyICsgMzU5OTkuMDUwMjkwOSAqIFRcCiAgICBsb2NhbCBNbSA9IDEzNC45NjMzOTY0ICsgNDc3MTk4Ljg2NzUwNTUgKiBUXApcCiAgICBsb2NhbCBpID0gMTgwIC0gRFwKICAgICAgICAtIDYuMjg5ICogc2luKHJhZChNbSkpXAogICAgICAgICsgMi4xMDAgKiBzaW4ocmFkKE1zKSlcCiAgICAgICAgLSAxLjI3NCAqIHNpbihyYWQoMiAqIEQgLSBNbSkpXAogICAgICAgIC0gMC42NTggKiBzaW4ocmFkKDIgKiBEKSlcCiAgICAgICAgLSAwLjIxNCAqIHNpbihyYWQoMiAqIE1tKSlcCiAgICAgICAgLSAwLjExMCAqIHNpbihyYWQoRCkpXApcCiAgICBsb2NhbCBsaXQgPSAoMSArIGNvcyhyYWQoaSkpKSAvIDJcCiAgICByZXR1cm4ge1wKICAgICAgICBhbmdsZSA9ICgxODAgLSBpKSAlIDM2MCwgICAgICAgICAgICAgIC0tIDAgbmV3LCAxODAgZnVsbFwKICAgICAgICBsaXQgPSBtYXRoLmZsb29yKGxpdCAqIDEwMCArIDAuNSksXAogICAgfVwKZW5kXApcCnJldHVybiBNXAoiLAogIH0sCiAgWzNdID0gewogICAgcGF0aCA9ICJtb29uL25hbWVzLmx1YSIsCiAgICBzb3VyY2UgPSAiLS0gTmFtZSBvZiB0aGUgcGhhc2UgZm9yIGFuIGVsb25nYXRpb24gYW5nbGUgKDAgbmV3LCAxODAgZnVsbCkuXApsb2NhbCBNID0ge31cClwKbG9jYWwgbGlzdCA9IHtcCiAgICBcIm5ldyBtb29uXCIsIFwid2F4aW5nIGNyZXNjZW50XCIsIFwiZmlyc3QgcXVhcnRlclwiLCBcIndheGluZyBnaWJib3VzXCIsXAogICAgXCJmdWxsIG1vb25cIiwgXCJ3YW5pbmcgZ2liYm91c1wiLCBcImxhc3QgcXVhcnRlclwiLCBcIndhbmluZyBjcmVzY2VudFwiLFwKfVwKXApmdW5jdGlvbiBNLm9mKGFuZ2xlKVwKICAgIHJldHVybiBsaXN0W21hdGguZmxvb3IoKGFuZ2xlICsgMjIuNSkgLyA0NSkgJSA4ICsgMV1cCmVuZFwKXApyZXR1cm4gTVwKIiwKICB9LAp9CmxvY2FsIHBheWxvYWQgPSB7CiAgZW50cnkgPSB7CiAgICBpZCA9ICJfX2VudHJ5X18iLAogICAgcGF0aCA9ICJtYWluLmx1YSIsCiAgICBzb3VyY2UgPSAiLS0gbW9vbjogcHJpbnQgdGhlIHBoYXNlIG9mIHRoZSBNb29uIGZvciBhIGRhdGUuXApsb2NhbCBwaGFzZSA9IHJlcXVpcmUoXCJtb29uLnBoYXNlXCIpXApsb2NhbCBuYW1lcyA9IHJlcXVpcmUoXCJtb29uLm5hbWVzXCIpXApcCmxvY2FsIGRhdGUgPSBhcmdbMV0gb3Igb3MuZGF0ZShcIiElWS0lbS0lZFwiKVwKbG9jYWwgcCA9IHBoYXNlLm9mKGRhdGUpXApcCnByaW50KChcIiVzICAlcyAgJWQlJSBsaXRcIik6Zm9ybWF0KGRhdGUsIG5hbWVzLm9mKHAuYW5nbGUpLCBwLmxpdCkpXAoiLAogIH0sCiAgbW9kdWxlcyA9IHsKICAgIFsibW9vbi5qdWxpYW4iXSA9IG1vZHVsZV9yZWNvcmRzWzFdLAogICAgWyJtb29uLm5hbWVzIl0gPSBtb2R1bGVfcmVjb3Jkc1szXSwKICAgIFsibW9vbi5waGFzZSJdID0gbW9kdWxlX3JlY29yZHNbMl0sCiAgfSwKfQpsb2NhbCBmdW5jdGlvbiBwYXRoRGlybmFtZShwYXRoKQogIHBhdGggPSB0b3N0cmluZyhwYXRoIG9yICIiKTpnc3ViKCJcXCIsICIvIikKICByZXR1cm4gcGF0aDptYXRjaCgiXiguKikvW14vXSskIikgb3IgIi4iCmVuZAoKbG9jYWwgZnVuY3Rpb24gam9pblBhdGgobGVmdCwgcmlnaHQpCiAgbGVmdCA9IHRvc3RyaW5nKGxlZnQgb3IgIiIpCiAgcmlnaHQgPSB0b3N0cmluZyhyaWdodCBvciAiIikKICBpZiByaWdodDpzdWIoMSwgMSkgPT0gIi8iIG9yIHJpZ2h0Om1hdGNoKCJeJWE6LyIpIHRoZW4gcmV0dXJuIHJpZ2h0IGVuZAogIGlmIGxlZnQgPT0gIiIgb3IgbGVmdCA9PSAiLiIgdGhlbiByZXR1cm4gcmlnaHQgZW5kCiAgcmV0dXJuIGxlZnQ6Z3N1YigiLyskIiwgIiIpIC4uICIvIiAuLiByaWdodAplbmQKCmxvY2FsIGZ1bmN0aW9uIGNvbmZpZ3VyZU5hdGl2ZVBhdGgobmF0aXZlX2RpciwgbGF1bmNoZXJfcGF0aCkKICBpZiBub3QgbmF0aXZlX2RpciBvciBuYXRpdmVfZGlyID09ICIiIHRoZW4gcmV0dXJuIGVuZAogIGxvY2FsIHJlc29sdmVkID0gam9pblBhdGgocGF0aERpcm5hbWUobGF1bmNoZXJfcGF0aCksIG5hdGl2ZV9kaXIpCiAgbG9jYWwgcGF0dGVybnMgPSB0YWJsZS5jb25jYXQoewogICAgcmVzb2x2ZWQgLi4gIi8/LnNvIiwKICAgIHJlc29sdmVkIC4uICIvPy9pbml0LnNvIiwKICAgIHJlc29sdmVkIC4uICIvPy5keWxpYiIsCiAgICByZXNvbHZlZCAuLiAiLz8vaW5pdC5keWxpYiIsCiAgICByZXNvbHZlZCAuLiAiLz8uZGxsIiwKICAgIHJlc29sdmVkIC4uICIvPy9pbml0LmRsbCIsCiAgfSwgIjsiKQogIHBhY2thZ2UuY3BhdGggPSBwYXR0ZXJucyAuLiAiOyIgLi4gcGFja2FnZS5jcGF0aAplbmQKCmxvY2FsIGZ1bmN0aW9uIHN0cmlwU291cmNlKHNvdXJjZSkKICBzb3VyY2UgPSB0b3N0cmluZyhzb3VyY2Ugb3IgIiIpCiAgaWYgc291cmNlOnN1YigxLCAzKSA9PSAiXDIzOVwxODdcMTkxIiB0aGVuIHNvdXJjZSA9IHNvdXJjZTpzdWIoNCkgZW5kCiAgaWYgc291cmNlOnN1YigxLCAyKSA9PSAiIyEiIHRoZW4KICAgIGxvY2FsIG5ld2xpbmVfc3RhcnQsIG5ld2xpbmVfZW5kID0gc291cmNlOmZpbmQoIlxyXG4iLCAxLCB0cnVlKQogICAgaWYgbm90IG5ld2xpbmVfc3RhcnQgdGhlbiBuZXdsaW5lX3N0YXJ0LCBuZXdsaW5lX2VuZCA9IHNvdXJjZTpmaW5kKCJbXHJcbl0iKSBlbmQKICAgIGlmIG5ld2xpbmVfc3RhcnQgdGhlbiBzb3VyY2UgPSAiXG4iIC4uIHNvdXJjZTpzdWIobmV3bGluZV9lbmQgKyAxKSBlbHNlIHNvdXJjZSA9ICIiIGVuZAogIGVuZAogIHJldHVybiBzb3VyY2UKZW5kCgpsb2NhbCBmdW5jdGlvbiBsb2FkZXJUYWJsZSgpCiAgcmV0dXJuIHBhY2thZ2Uuc2VhcmNoZXJzIG9yIHBhY2thZ2UubG9hZGVycwplbmQKCmxvY2FsIHVucGFja1ZhbHVlcyA9IHRhYmxlLnVucGFjayBvciB1bnBhY2sKCmxvY2FsIGZ1bmN0aW9uIHBhY2tWYWx1ZXMoLi4uKQogIHJldHVybiB7IG4gPSBzZWxlY3QoIiMiLCAuLi4pLCAuLi4gfQplbmQKCmxvY2FsIGZ1bmN0aW9uIGxvYWRUZXh0KHNvdXJjZSwgY2h1bmtfbmFtZSkKICBpZiB0eXBlKHNvdXJjZSkgfj0gInN0cmluZyIgdGhlbiByZXR1cm4gbmlsLCAic291cmNlIG11c3QgYmUgYSBzdHJpbmciIGVuZAogIGlmIHNvdXJjZTpieXRlKDEpID09IDI3IHRoZW4gcmV0dXJuIG5pbCwgImJpbmFyeSBjaHVua3MgYXJlIG5vdCBhY2NlcHRlZCIgZW5kCiAgaWYgX1ZFUlNJT04gPT0gIkx1YSA1LjEiIHRoZW4gcmV0dXJuIGxvYWRzdHJpbmcoc291cmNlLCBjaHVua19uYW1lKSBlbmQKICByZXR1cm4gbG9hZChzb3VyY2UsIGNodW5rX25hbWUsICJ0IikKZW5kCgpsb2NhbCBmdW5jdGlvbiBsb2FkUGF5bG9hZFNvdXJjZShyZWNvcmQsIGNodW5rX25hbWUpCiAgbG9jYWwgbG9hZGVyLCBlcnIgPSBsb2FkVGV4dChzdHJpcFNvdXJjZShyZWNvcmQuc291cmNlIG9yICIiKSwgY2h1bmtfbmFtZSBvciAoIkAiIC4uIHRvc3RyaW5nKHJlY29yZC5wYXRoIG9yICJidW5kbGUiKSkpCiAgaWYgbm90IGxvYWRlciB0aGVuIGVycm9yKGVycikgZW5kCiAgcmV0dXJuIGxvYWRlcgplbmQKCmxvY2FsIGZ1bmN0aW9uIHJlc3RvcmVMb2FkZWRNb2R1bGVzKGxvYWRlZCwgcHJldmlvdXNfbW9kdWxlcykKICBmb3IgbmFtZSwgcHJldmlvdXMgaW4gcGFpcnMocHJldmlvdXNfbW9kdWxlcykgZG8KICAgIGlmIHByZXZpb3VzLnByZXNlbnQgdGhlbiByYXdzZXQobG9hZGVkLCBuYW1lLCBwcmV2aW91cy52YWx1ZSkKICAgIGVsc2UgcmF3c2V0KGxvYWRlZCwgbmFtZSwgbmlsKSBlbmQKICBlbmQKZW5kCgpsb2NhbCBmdW5jdGlvbiBpbnN0YWxsKHBheWxvYWQpCiAgbG9jYWwgbW9kdWxlcyA9IHBheWxvYWQubW9kdWxlcyBvciB7fQogIGxvY2FsIHNlYXJjaGVycyA9IGxvYWRlclRhYmxlKCkKICBsb2NhbCBzZWFyY2hlcgogIHNlYXJjaGVyID0gZnVuY3Rpb24obW9kdWxlX25hbWUpCiAgICBsb2NhbCByZWNvcmQgPSBtb2R1bGVzW21vZHVsZV9uYW1lXQogICAgaWYgbm90IHJlY29yZCB0aGVuIHJldHVybiAiXG5cdG5vIGJ1bmRsZWQgbW9kdWxlICciIC4uIHRvc3RyaW5nKG1vZHVsZV9uYW1lKSAuLiAiJyIgZW5kCiAgICByZXR1cm4gbG9hZFBheWxvYWRTb3VyY2UocmVjb3JkLCAiQCIgLi4gdG9zdHJpbmcocmVjb3JkLnBhdGggb3IgbW9kdWxlX25hbWUpKSwgcmVjb3JkLnBhdGgKICBlbmQKICB0YWJsZS5pbnNlcnQoc2VhcmNoZXJzLCAyLCBzZWFyY2hlcikKICByZXR1cm4gZnVuY3Rpb24oKQogICAgZm9yIGkgPSAjc2VhcmNoZXJzLCAxLCAtMSBkbwogICAgICBpZiBzZWFyY2hlcnNbaV0gPT0gc2VhcmNoZXIgdGhlbiB0YWJsZS5yZW1vdmUoc2VhcmNoZXJzLCBpKTsgYnJlYWsgZW5kCiAgICBlbmQKICBlbmQKZW5kCgpsb2NhbCBmdW5jdGlvbiBydW4ocGF5bG9hZCwgcnVuX2FyZ3MsIGFwcGxpY2F0aW9uX2FyZzApCiAgbG9jYWwgbG9hZGVkID0gcGFja2FnZS5sb2FkZWQKICBsb2NhbCBwcmV2aW91c19tb2R1bGVzID0ge30KICBmb3IgbmFtZSBpbiBwYWlycyhwYXlsb2FkLm1vZHVsZXMgb3Ige30pIGRvCiAgICBsb2NhbCB2YWx1ZSA9IHJhd2dldChsb2FkZWQsIG5hbWUpCiAgICBwcmV2aW91c19tb2R1bGVzW25hbWVdID0geyBwcmVzZW50ID0gdmFsdWUgfj0gbmlsLCB2YWx1ZSA9IHZhbHVlIH0KICAgIHJhd3NldChsb2FkZWQsIG5hbWUsIG5pbCkKICBlbmQKICBsb2NhbCBpbnN0YWxsX29rLCB1bmluc3RhbGwgPSBwY2FsbChpbnN0YWxsLCBwYXlsb2FkKQogIGlmIG5vdCBpbnN0YWxsX29rIHRoZW4KICAgIHJlc3RvcmVMb2FkZWRNb2R1bGVzKGxvYWRlZCwgcHJldmlvdXNfbW9kdWxlcykKICAgIGVycm9yKHVuaW5zdGFsbCwgMCkKICBlbmQKICBsb2NhbCBvbGRfYXJnID0gX0cuYXJnCiAgbG9jYWwgZW50cnkgPSBwYXlsb2FkLmVudHJ5CiAgbG9jYWwgcnVudGltZV9hcmcgPSB7IFswXSA9IGFwcGxpY2F0aW9uX2FyZzAKICAgICAgb3IgKHR5cGUob2xkX2FyZykgPT0gInRhYmxlIiBhbmQgb2xkX2FyZ1swXSkKICAgICAgb3IgZW50cnkucGF0aCBvciBlbnRyeS5pZCBvciAiX19lbnRyeV9fIiB9CiAgZm9yIGkgPSAxLCAjKHJ1bl9hcmdzIG9yIHt9KSBkbyBydW50aW1lX2FyZ1tpXSA9IHJ1bl9hcmdzW2ldIGVuZAogIF9HLmFyZyA9IHJ1bnRpbWVfYXJnCiAgbG9jYWwgcmVzdWx0cyA9IHBhY2tWYWx1ZXMocGNhbGwoZnVuY3Rpb24oKQogICAgcmV0dXJuIGxvYWRQYXlsb2FkU291cmNlKGVudHJ5LCAiQCIgLi4gdG9zdHJpbmcoZW50cnkucGF0aCBvciBlbnRyeS5pZCBvciAiX19lbnRyeV9fIikpKCkKICBlbmQpKQogIF9HLmFyZyA9IG9sZF9hcmcKICBsb2NhbCB1bmluc3RhbGxfb2ssIHVuaW5zdGFsbF9lcnIgPSBwY2FsbCh1bmluc3RhbGwpCiAgcmVzdG9yZUxvYWRlZE1vZHVsZXMobG9hZGVkLCBwcmV2aW91c19tb2R1bGVzKQogIGlmIG5vdCByZXN1bHRzWzFdIHRoZW4gZXJyb3IocmVzdWx0c1syXSwgMCkgZW5kCiAgaWYgbm90IHVuaW5zdGFsbF9vayB0aGVuIGVycm9yKHVuaW5zdGFsbF9lcnIsIDApIGVuZAogIHJldHVybiB1bnBhY2tWYWx1ZXMocmVzdWx0cywgMiwgcmVzdWx0cy5uKQplbmQKCmxvY2FsIGFwcGxpY2F0aW9uX2FyZzAgPSBhcmcgYW5kIGFyZ1swXSBvciAiIgpsb2NhbCBsYXVuY2hlcl9wYXRoID0gcmF3Z2V0KF9HLCAiX19sdWFpX2V4ZWN1dGFibGVfcGF0aCIpIG9yIGFwcGxpY2F0aW9uX2FyZzAKcmF3c2V0KF9HLCAiX19sdWFpX2V4ZWN1dGFibGVfcGF0aCIsIG5pbCkKY29uZmlndXJlTmF0aXZlUGF0aCgiLmx1YWkvbmF0aXZlIiwgbGF1bmNoZXJfcGF0aCkKbG9jYWwgcnVuX2FyZ3MgPSB7fQppZiBhcmcgdGhlbiBmb3IgaSA9IDEsICNhcmcgZG8gcnVuX2FyZ3NbaV0gPSBhcmdbaV0gZW5kIGVuZApyZXR1cm4gcnVuKHBheWxvYWQsIHJ1bl9hcmdzLCBhcHBsaWNhdGlvbl9hcmcwKQAAAAA0GwAAAAAAAF9fdG9zdHJpbmcAAAAAAAAoZXJyb3Igb2JqZWN0IGlzIG5vdCBhIHN0cmluZykAUEFUSAAuLyVzACUuKnMvJXMAL3Byb2Mvc2VsZi9leGUAAGFyZwBfX2x1YWlfZXhlY3V0YWJsZV9wYXRoAHQAQGx1YWluc3RhbGxlci1ib290c3RyYXAAX1ZFUlNJT04ATHVhIDUuNAAAbHVhaW5zdGFsbGVyOiBjYW5ub3QgY3JlYXRlIEx1YSBzdGF0ZQoAAGx1YWluc3RhbGxlcjogbGlua2VkIEx1YSBydW50aW1lIGlzIG5vdCBMdWEgNS40CgB1bmtub3duIGxhdW5jaGVyIGVycm9yAGx1YWluc3RhbGxlcjogJXMKAAAAARsDO2gAAAAMAAAARM7//6wAAAAU0P//hAAAAETQ//+YAAAA+tD//9QAAACG0f//9AAAAPLR//8UAQAAgtL//zQBAAA/1P//VAEAALbU//90AQAAK9b//5QBAABa1v//tAEAANLW///UAQAAFAAAAAAAAAABelIAAXgQARsMBwiQAQAAEAAAABwAAACIz///JgAAAABEBxAQAAAAMAAAAKTP//8FAAAAAAAAACQAAABEAAAAkM3//9ABAAAADhBGDhhKDwt3CIAAPxo7KjMkIgAAAAAcAAAAbAAAAB7Q//+MAAAAAEEOEIYCQw0GAocMBwgAABwAAACMAAAAitD//2wAAAAAQQ4QhgJDDQYCZwwHCAAAHAAAAKwAAADW0P//kAAAAABBDhCGAkMNBgKLDAcIAAAcAAAAzAAAAEbR//+9AQAAAEEOEIYCQw0GA7gBDAcIABwAAADsAAAA49L//3cAAAAAQQ4QhgJDDQYCcgwHCAAAHAAAAAwBAAA60///dQEAAABBDhCGAkMNBgNwAQwHCAAcAAAALAEAAI/U//8vAAAAAEEOEIYCQw0GagwHCAAAABwAAABMAQAAntT//3gAAAAAQQ4QhgJDDQYCcwwHCAAAHAAAAGwBAAD21P//jwEAAABBDhCGAkMNBgOKAQwHCAAAAAAAAAAAAAQAAAAwAAAABQAAAEdOVQACgADABAAAAAEAAAAAAAAAAQABwAQAAAABAAAAAAAAAAIAAcAEAAAAAQAAAAAAAAAEAAAAEAAAAAEAAABHTlUAAAAAAAMAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAZAAAAAAADgBUAAAAAAAAEAAAAAAAAAYQEAAAAAAAABAAAAAAAAAG8BAAAAAAAAAQAAAAAAAAB5AQAAAAAAAB0AAAAAAAAArwEAAAAAAAAMAAAAAAAAADwDQAAAAAAADQAAAAAAAACADUAAAAAAABkAAAAAAAAAyE1AAAAAAAAbAAAAAAAAAAgAAAAAAAAAGgAAAAAAAADQTUAAAAAAABwAAAAAAAAACAAAAAAAAAD1/v9vAAAAACAQQAAAAAAABQAAAAAAAABIE0AAAAAAAAYAAAAAAAAASBBAAAAAAAAKAAAAAAAAAMQBAAAAAAAACwAAAAAAAAAYAAAAAAAAABUAAAAAAAAAAAAAAAAAAAADAAAAAAAAAOhPQAAAAAAAAgAAAAAAAACgAgAAAAAAABQAAAAAAAAABwAAAAAAAAAXAAAAAAAAAOgVQAAAAAAABwAAAAAAAACgFUAAAAAAAAgAAAAAAAAASAAAAAAAAAAJAAAAAAAAABgAAAAAAAAA/v//bwAAAABQFUAAAAAAAP///28AAAAAAQAAAAAAAADw//9vAAAAAAwVQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANhNQAAAAAAAAAAAAAAAAAAAAAAAAAAAAHYDQAAAAAAAhgNAAAAAAACWA0AAAAAAAKYDQAAAAAAAtgNAAAAAAADGA0AAAAAAANYDQAAAAAAA5gNAAAAAAAD2A0AAAAAAAAYEQAAAAAAAFgRAAAAAAAAmBEAAAAAAADYEQAAAAAAARgRAAAAAAABWBEAAAAAAAGYEQAAAAAAAdgRAAAAAAACGBEAAAAAAAJYEQAAAAAAApgRAAAAAAAC2BEAAAAAAAMYEQAAAAAAA1gRAAAAAAADmBEAAAAAAAPYEQAAAAAAABgVAAAAAAAAWBUAAAAAAACYFQAAAAAAAAAAAAEdDQzogKEdOVSkgMTYuMi4xIDIwMjYwODE5IChSZWQgSGF0IDE2LjIuMS0yKQBBVjo0cDEzMTQAUlY6cnVubmluZyBnY2MgMTYuMi4xIDIwMjYwODE5AEJWOmFubm9iaW4gZ2NjIDE2LjIuMSAyMDI2MDgxOQBHVzoweDdkNjA1NjIgLi4vc3lzZGVwcy94ODYvYWJpLW5vdGUuYwBTUDozAFNDOjEAQ0Y6OCAuLi9zeXNkZXBzL3g4Ni9hYmktbm90ZS5jAEZMOjAgLi4vc3lzZGVwcy94ODYvYWJpLW5vdGUuYwBHQToxAFBJOjQAU0U6MABpUzowAEdXOjB4N2Q2MDU2MiBpbml0LmMAQ0Y6OCBpbml0LmMARkw6MCBpbml0LmMAR1c6MHg3ZDYwNTYyIHN0YXRpYy1yZWxvYy5jAFNQOjAgc3RhdGljLXJlbG9jLmMAQ0Y6OCBzdGF0aWMtcmVsb2MuYwBGTDowIHN0YXRpYy1yZWxvYy5jAAAAAAgAAAAQAAAAAAEAAEdBJAEzYTEAMAVAAAAAAABWBUAAAAAAAAgAAAAQAAAAAAEAAEdBJAEzYTEAZQVAAAAAAABlBUAAAAAAAAgAAAAQAAAAAAEAAEdBJAEzYTEAPANAAAAAAABSA0AAAAAAAAgAAAAQAAAAAAEAAEdBJAEzYTEAgA1AAAAAAACIDUAAAAAAAAgAAAAQAAAAAAEAAEdBJAEzYTEAcAVAAAAAAAAWBkAAAAAAAAgAAAAQAAAAAAEAAEdBJAEzYTEAfQ1AAAAAAAB9DUAAAAAAAAgAAAAQAAAAAAEAAEdBJAEzYTEAfQ1AAAAAAAB9DUAAAAAAAAgAAAAQAAAAAAEAAEdBJAEzYTEAUgNAAAAAAABXA0AAAAAAAAgAAAAQAAAAAAEAAEdBJAEzYTEAiA1AAAAAAACNDUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAEAPH/AAAAAAAAAAAAAAAAAAAAAAgAAAABABIAWDdAAAAAAAAgAAAAAAAAABIAAAAEAPH/AAAAAAAAAAAAAAAAAAAAAB0AAAACAAQAcAVAAAAAAAAAAAAAAAAAAB8AAAACAAQAoAVAAAAAAAAAAAAAAAAAADIAAAACAAQA4AVAAAAAAAAAAAAAAAAAAEgAAAABABkACFFAAAAAAAABAAAAAAAAAFQAAAABABQA0E1AAAAAAAAAAAAAAAAAAHsAAAACAAQAEAZAAAAAAAAAAAAAAAAAAIcAAAABABMAyE1AAAAAAAAAAAAAAAAAAKYAAAAEAPH/AAAAAAAAAAAAAAAAAAAAALEAAAABAA4AwBhAAAAAAAA0GwAAAAAAAMAAAAABAA4A+DNAAAAAAAAIAAAAAAAAANQAAAACAAQAFgZAAAAAAACMAAAAAAAAAOMAAAACAAQAogZAAAAAAABsAAAAAAAAAPIAAAACAAQADgdAAAAAAACQAAAAAAAAAAcBAAACAAQAngdAAAAAAAC9AQAAAAAAACIBAAACAAQAWwlAAAAAAAB3AAAAAAAAADcBAAACAAQA0glAAAAAAAB1AQAAAAAAAEUBAAACAAQARwtAAAAAAAAvAAAAAAAAAFkBAAACAAQAdgtAAAAAAAB4AAAAAAAAAG4BAAAEAPH/AAAAAAAAAAAAAAAAAAAAAHcBAAABABAAEDdAAAAAAAAAAAAAAAAAAAAAAAAEAPH/AAAAAAAAAAAAAAAAAAAAAIUBAAABABUA2E1AAAAAAAAAAAAAAAAAAI4BAAAAAA8AHDVAAAAAAAAAAAAAAAAAAKEBAAABABcA6E9AAAAAAAAAAAAAAAAAALcBAAASAAAAAAAAAAAAAAAAAAAAAAAAAMoBAAASAAAAAAAAAAAAAAAAAAAAAAAAANUBAAASAAAAAAAAAAAAAAAAAAAAAAAAAOABAAASAAAAAAAAAAAAAAAAAAAAAAAAAP0BAAASAAAAAAAAAAAAAAAAAAAAAAAAAN8CAAAgABgA4FBAAAAAAAAAAAAAAAAAAAwCAAASAAAAAAAAAAAAAAAAAAAAAAAAABoCAAASAAAAAAAAAAAAAAAAAAAAAAAAACsCAAASAAAAAAAAAAAAAAAAAAAAAAAAADwCAAASAAAAAAAAAAAAAAAAAAAAAAAAAFECAAASAAAAAAAAAAAAAAAAAAAAAAAAAFsCAAASAAAAAAAAAAAAAAAAAAAAAAAAAGkCAAAQABgA5FBAAAAAAAAAAAAAAAAAAHACAAASAAAAAAAAAAAAAAAAAAAAAAAAAIACAAASAgUAgA1AAAAAAAAAAAAAAAAAAIYCAAASAAAAAAAAAAAAAAAAAAAAAAAAAJkCAAASAAAAAAAAAAAAAAAAAAAAAAAAAKwCAAASAAAAAAAAAAAAAAAAAAAAAAAAAMECAAASAAAAAAAAAAAAAAAAAAAAAAAAAM8CAAASAAAAAAAAAAAAAAAAAAAAAAAAAN0CAAAQABgA4FBAAAAAAAAAAAAAAAAAAOoCAAASAAAAAAAAAAAAAAAAAAAAAAAAAP0CAAASAAAAAAAAAAAAAAAAAAAAAAAAAAsDAAASAAAAAAAAAAAAAAAAAAAAAAAAAB8DAAASAAAAAAAAAAAAAAAAAAAAAAAAACsDAAAgAAAAAAAAAAAAAAAAAAAAAAAAADoDAAARAg4AqBhAAAAAAAAAAAAAAAAAAEcDAAASAAAAAAAAAAAAAAAAAAAAAAAAAFoDAAASAAAAAAAAAAAAAAAAAAAAAAAAAGwDAAARAA4AoBhAAAAAAAAEAAAAAAAAAHsDAAASAAAAAAAAAAAAAAAAAAAAAAAAAIkDAAAQABkAEFFAAAAAAAAAAAAAAAAAAI4DAAASAgQAYAVAAAAAAAAFAAAAAAAAAOMCAAASAAQAMAVAAAAAAAAmAAAAAAAAAKYDAAAQABkAAFFAAAAAAAAAAAAAAAAAALIDAAASAAQA7gtAAAAAAACPAQAAAAAAALcDAAASAAAAAAAAAAAAAAAAAAAAAAAAAMoDAAASAAAAAAAAAAAAAAAAAAAAAAAAANMDAAASAAAAAAAAAAAAAAAAAAAAAAAAAOYDAAARAhgA6FBAAAAAAAAAAAAAAAAAAPIDAAASAAAAAAAAAAAAAAAAAAAAAAAAAAEEAAASAgIAPANAAAAAAAAAAAAAAAAAAAcEAAASAAAAAAAAAAAAAAAAAAAAAAAAABIEAAARABkAAFFAAAAAAAAIAAAAAAAAAABjcnQxLm8AX19hYmlfdGFnAGNydGJlZ2luLm8AZGVyZWdpc3Rlcl90bV9jbG9uZXMAX19kb19nbG9iYWxfZHRvcnNfYXV4AGNvbXBsZXRlZC4wAF9fZG9fZ2xvYmFsX2R0b3JzX2F1eF9maW5pX2FycmF5X2VudHJ5AGZyYW1lX2R1bW15AF9fZnJhbWVfZHVtbXlfaW5pdF9hcnJheV9lbnRyeQBsYXVuY2hlci5jAGx1YWlfYm9vdHN0cmFwAGx1YWlfYm9vdHN0cmFwX3NpemUAbHVhaV90cmFjZWJhY2sAbHVhaV9jb3B5X3BhdGgAbHVhaV9yZWFsX2V4ZWN1dGFibGUAbHVhaV9leGVjdXRhYmxlX2Zyb21fYXJndjAAbHVhaV9leGVjdXRhYmxlX3BhdGgAbHVhaV9wdXNoX2FyZwBsdWFpX2xvYWRfYm9vdHN0cmFwAGx1YWlfcnVudGltZV9tYXRjaGVzAGNydGVuZC5vAF9fRlJBTUVfRU5EX18AX0RZTkFNSUMAX19HTlVfRUhfRlJBTUVfSERSAF9HTE9CQUxfT0ZGU0VUX1RBQkxFXwBnZXRlbnZAR0xJQkNfMi4yLjUAbHVhX2dldHRvcABsdWFfc2V0dG9wAF9fbGliY19zdGFydF9tYWluQEdMSUJDXzIuMzQAbHVhTF90cmFjZWJhY2sAbHVhTF9jYWxsbWV0YQBsdWFfcHVzaGNjbG9zdXJlAGx1YUxfbG9hZGJ1ZmZlcngAcmVhZGxpbmtAR0xJQkNfMi4yLjUAbHVhX2Nsb3NlAGx1YV90b2xzdHJpbmcAX2VkYXRhAGx1YV9jcmVhdGV0YWJsZQBfZmluaQBzdHJsZW5AR0xJQkNfMi4yLjUAc3RyY2hyQEdMSUJDXzIuMi41AHNucHJpbnRmQEdMSUJDXzIuMi41AGx1YUxfb3BlbmxpYnMAbHVhX3NldGdsb2JhbABfX2RhdGFfc3RhcnQAc3RyY21wQEdMSUJDXzIuMi41AGx1YUxfbmV3c3RhdGUAZnByaW50ZkBHTElCQ18yLjIuNQBsdWFfcmF3c2V0aQBfX2dtb25fc3RhcnRfXwBfX2Rzb19oYW5kbGUAcmVhbHBhdGhAR0xJQkNfMi4zAG1lbWNweUBHTElCQ18yLjE0AF9JT19zdGRpbl91c2VkAGx1YV9nZXRnbG9iYWwAX2VuZABfZGxfcmVsb2NhdGVfc3RhdGljX3BpZQBfX2Jzc19zdGFydABtYWluAGFjY2Vzc0BHTElCQ18yLjIuNQBsdWFfdHlwZQBmd3JpdGVAR0xJQkNfMi4yLjUAX19UTUNfRU5EX18AbHVhX3B1c2hzdHJpbmcAX2luaXQAbHVhX3BjYWxsawBzdGRlcnJAR0xJQkNfMi4yLjUAAC5zeW10YWIALnN0cnRhYgAuc2hzdHJ0YWIALm5vdGUuZ251LmJ1aWxkLWlkAC5pbml0AC50ZXh0AC5maW5pAC5pbnRlcnAALmdudS5oYXNoAC5keW5zeW0ALmR5bnN0cgAuZ251LnZlcnNpb24ALmdudS52ZXJzaW9uX3IALnJlbGEuZHluAC5yZWxhLnBsdAAucm9kYXRhAC5laF9mcmFtZV9oZHIALmVoX2ZyYW1lAC5ub3RlLmdudS5wcm9wZXJ0eQAubm90ZS5BQkktdGFnAC5pbml0X2FycmF5AC5maW5pX2FycmF5AC5keW5hbWljAC5nb3QALmdvdC5wbHQALmRhdGEALmJzcwAuY29tbWVudAAuYW5ub2Jpbi5ub3RlcwAuZ251LmJ1aWxkLmF0dHJpYnV0ZXMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABsAAAAHAAAAAgAAAAAAAAAYA0AAAAAAABgDAAAAAAAAJAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAuAAAAAQAAAAYAAAAAAAAAPANAAAAAAAA8AwAAAAAAABsAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAjQAAAAEAAAAGAAAAAAAAAGADQAAAAAAAYAMAAAAAAADQAQAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAADQAAAABAAAABgAAAAAAAAAwBUAAAAAAADAFAAAAAAAATQgAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAA6AAAAAQAAAAYAAAAAAAAAgA1AAAAAAACADQAAAAAAAA0AAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAQAAAAAEAAAACAAAAAAAAAAAQQAAAAAAAABAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAEgAAAD2//9vAgAAAAAAAAAgEEAAAAAAACAQAAAAAAAAJAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAAAAAAAAAAAABSAAAACwAAAAIAAAAAAAAASBBAAAAAAABIEAAAAAAAAAADAAAAAAAACQAAAAEAAAAIAAAAAAAAABgAAAAAAAAAWgAAAAMAAAACAAAAAAAAAEgTQAAAAAAASBMAAAAAAADEAQAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAGIAAAD///9vAgAAAAAAAAAMFUAAAAAAAAwVAAAAAAAAQAAAAAAAAAAIAAAAAAAAAAIAAAAAAAAAAgAAAAAAAABvAAAA/v//bwIAAAAAAAAAUBVAAAAAAABQFQAAAAAAAFAAAAAAAAAACQAAAAEAAAAIAAAAAAAAAAAAAAAAAAAAfgAAAAQAAAACAAAAAAAAAKAVQAAAAAAAoBUAAAAAAABIAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAYAAAAAAAAAIgAAAAEAAAAQgAAAAAAAADoFUAAAAAAAOgVAAAAAAAAoAIAAAAAAAAIAAAAFwAAAAgAAAAAAAAAGAAAAAAAAACSAAAAAQAAAAIAAAAAAAAAoBhAAAAAAACgGAAAAAAAAHocAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAmgAAAAEAAAACAAAAAAAAABw1QAAAAAAAHDUAAAAAAABsAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAKgAAAABAAAAAgAAAAAAAACINUAAAAAAAIg1AAAAAAAAjAEAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAACyAAAABwAAAAIAAAAAAAAAGDdAAAAAAAAYNwAAAAAAAEAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAxQAAAAcAAAACAAAAAAAAAFg3QAAAAAAAWDcAAAAAAAAgAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAANMAAAAOAAAAAwAAAAAAAADITUAAAAAAAMg9AAAAAAAACAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAAAAAAADfAAAADwAAAAMAAAAAAAAA0E1AAAAAAADQPQAAAAAAAAgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA6wAAAAYAAAADAAAAAAAAANhNQAAAAAAA2D0AAAAAAAAAAgAAAAAAAAkAAAAAAAAACAAAAAAAAAAQAAAAAAAAAPQAAAABAAAAAwAAAAAAAADYT0AAAAAAANg/AAAAAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAAAAAAAD5AAAAAQAAAAMAAAAAAAAA6E9AAAAAAADoPwAAAAAAAPgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAAAgEAAAEAAAADAAAAAAAAAOBQQAAAAAAA4EAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAgBAAAIAAAAAwAAAAAAAAAAUUAAAAAAAORAAAAAAAAAEAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAANAQAAAQAAADAAAAAAAAAAAAAAAAAAAADkQAAAAAAAAC4AAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAFgEAAAEAAAAwAAAAAAAAAAAAAAAAAAAAEkEAAAAAAABPAQAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAACUBAAAHAAAAAAAAAAAAAAAQcUAAAAAAAGRCAAAAAAAARAEAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAABAAAAAgAAAAAAAAAAAAAAAAAAAAAAAACoQwAAAAAAAMAGAAAAAAAAHgAAABwAAAAIAAAAAAAAABgAAAAAAAAACQAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAaEoAAAAAAAAlBAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAABEAAAADAAAAAAAAAAAAAAAAAAAAAAAAAI1OAAAAAAAAOwEAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAA=",
  "sha": "2eda4a9aa949ff47b13b19e3595fe82cd660430fef0fed55d6daffc687e6dcbe",
  "sections": [
   {
    "name": ".note.gnu.build-id",
    "off": 792,
    "size": 36
   },
   {
    "name": ".init",
    "off": 828,
    "size": 27
   },
   {
    "name": ".plt",
    "off": 864,
    "size": 464
   },
   {
    "name": ".text",
    "off": 1328,
    "size": 2125
   },
   {
    "name": ".fini",
    "off": 3456,
    "size": 13
   },
   {
    "name": ".interp",
    "off": 4096,
    "size": 28
   },
   {
    "name": ".gnu.hash",
    "off": 4128,
    "size": 36
   },
   {
    "name": ".dynsym",
    "off": 4168,
    "size": 768
   },
   {
    "name": ".dynstr",
    "off": 4936,
    "size": 452
   },
   {
    "name": ".gnu.version",
    "off": 5388,
    "size": 64
   },
   {
    "name": ".gnu.version_r",
    "off": 5456,
    "size": 80
   },
   {
    "name": ".rela.dyn",
    "off": 5536,
    "size": 72
   },
   {
    "name": ".rela.plt",
    "off": 5608,
    "size": 672
   },
   {
    "name": ".rodata",
    "off": 6304,
    "size": 7290
   },
   {
    "name": ".eh_frame_hdr",
    "off": 13596,
    "size": 108
   },
   {
    "name": ".eh_frame",
    "off": 13704,
    "size": 396
   },
   {
    "name": ".note.gnu.property",
    "off": 14104,
    "size": 64
   },
   {
    "name": ".note.ABI-tag",
    "off": 14168,
    "size": 32
   },
   {
    "name": ".init_array",
    "off": 15816,
    "size": 8
   },
   {
    "name": ".fini_array",
    "off": 15824,
    "size": 8
   },
   {
    "name": ".dynamic",
    "off": 15832,
    "size": 512
   },
   {
    "name": ".got",
    "off": 16344,
    "size": 16
   },
   {
    "name": ".got.plt",
    "off": 16360,
    "size": 248
   },
   {
    "name": ".data",
    "off": 16608,
    "size": 4
   },
   {
    "name": ".bss",
    "off": 16612,
    "size": 16
   },
   {
    "name": ".comment",
    "off": 16612,
    "size": 46
   },
   {
    "name": ".annobin.notes",
    "off": 16658,
    "size": 335
   },
   {
    "name": ".gnu.build.attributes",
    "off": 16996,
    "size": 324
   },
   {
    "name": ".symtab",
    "off": 17320,
    "size": 1728
   },
   {
    "name": ".strtab",
    "off": 19048,
    "size": 1061
   },
   {
    "name": ".shstrtab",
    "off": 20109,
    "size": 315
   }
  ],
  "shoff": 20424,
  "boot_off": 6336,
  "src_off": 8519,
  "xxd_src": [
   "00002140: 6461 7465 2e5c 0a6c 6f63 616c 2070 6861  date.\\.local pha",
   "00002150: 7365 203d 2072 6571 7569 7265 285c 226d  se = require(\\\"m",
   "00002160: 6f6f 6e2e 7068 6173 655c 2229 5c0a 6c6f  oon.phase\\\")\\.lo",
   "00002170: 6361 6c20 6e61 6d65 7320 3d20 7265 7175  cal names = requ",
   "00002180: 6972 6528 5c22 6d6f 6f6e 2e6e 616d 6573  ire(\\\"moon.names",
   "00002190: 5c22 295c 0a5c 0a6c 6f63 616c 2064 6174  \\\")\\.\\.local dat",
   "000021a0: 6520 3d20 6172 675b 315d 206f 7220 6f73  e = arg[1] or os",
   "000021b0: 2e64 6174 6528 5c22 2125 592d 256d 2d25  .date(\\\"!%Y-%m-%",
   "000021c0: 645c 2229 5c0a 6c6f 6361 6c20 7020 3d20  d\\\")\\.local p = ",
   "000021d0: 7068 6173 652e 6f66 2864 6174 6529 5c0a  phase.of(date)\\.",
   "000021e0: 5c0a 7072 696e 7428 285c 2225 7320 2025  \\.print((\\\"%s  %",
   "000021f0: 7320 2025 6425 2520 6c69 745c 2229 3a66  s  %d%% lit\\\"):f"
  ],
  "xxd_head": [
   "00000000: 7f45 4c46 0201 0100 0000 0000 0000 0000  .ELF............",
   "00000010: 0200 3e00 0100 0000 3005 4000 0000 0000  ..>.....0.@.....",
   "00000020: 4000 0000 0000 0000 c84f 0000 0000 0000  @........O......",
   "00000030: 0000 0000 4000 3800 0d00 4000 2000 1f00  ....@.8...@. ..."
  ],
  "main": [
   {
    "addr": "400bee",
    "bytes": "55",
    "asm": "push %rbp"
   },
   {
    "addr": "400bef",
    "bytes": "48 89 e5",
    "asm": "mov %rsp,%rbp"
   },
   {
    "addr": "400bf2",
    "bytes": "48 83 ec 30",
    "asm": "sub $0x30,%rsp"
   },
   {
    "addr": "400bf6",
    "bytes": "89 7d dc",
    "asm": "mov %edi,-0x24(%rbp)"
   },
   {
    "addr": "400bf9",
    "bytes": "48 89 75 d0",
    "asm": "mov %rsi,-0x30(%rbp)"
   },
   {
    "addr": "400bfd",
    "bytes": "e8 7e f8 ff ff",
    "asm": "call 400480 <luaL_newstate@plt>"
   }
  ],
  "calls": [
   {
    "addr": "400bfd",
    "bytes": "e8 7e f8 ff ff",
    "asm": "call 400480 <luaL_newstate@plt>"
   },
   {
    "addr": "400c3c",
    "bytes": "e8 0f f8 ff ff",
    "asm": "call 400450 <luaL_openlibs@plt>"
   },
   {
    "addr": "400c95",
    "bytes": "e8 38 fd ff ff",
    "asm": "call 4009d2 <luai_push_arg>"
   },
   {
    "addr": "400cc6",
    "bytes": "e8 7c fe ff ff",
    "asm": "call 400b47 <luai_load_bootstrap>"
   },
   {
    "addr": "400cf6",
    "bytes": "e8 25 f8 ff ff",
    "asm": "call 400520 <lua_pcallk@plt>"
   }
  ],
  "main_addr": "400bee",
  "file": "build/moon/moon: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=7093e02b2c91b4aa6fcd82a1ee8f5abe7e51cf94, for GNU/Linux 3.2.0, not stripped"
 },
 "marker": [
  "luainstaller-generated-output-v2",
  "output_dir=/home/waterrun/moon/build/moon",
  "dir\t.luai",
  "dir\t.luai/build",
  "file\t.luai/build/RELINKING.adoc\tdaae4a5ba6c99c0494839d0118d4d76f464799cb7d36d388094ac9a6735fd1bf",
  "file\t.luai/build/generate-onefile-payload.lua\tab5686e4dea681a08447d53e7fa33f37d2566ce1d03d3869cb00f47c7a2ce5f8",
  "file\t.luai/build/launcher.c\tfd1e6926a7222e5554fc50f4a15b389eab979fb4dcbe29f4bf1c908bcdc90696",
  "dir\t.luai/licenses",
  "file\t.luai/licenses/GPL-3.0-or-later.txt\t3972dc9744f6499f0f9b2dbf76696f2ae7ad8af9b23dde66d6af86c9dfb36986",
  "file\t.luai/licenses/LGPL-3.0-or-later.txt\te3a994d82e644b03a792a930f574002658412f62407f5fee083f2555c5f23118",
  "file\t.luai/licenses/Lua-MIT.txt\ta23ad1f0b07e4e59009d8efaaf1f5ed1dcd06e5256c1743a58ca4f1cacad32e0",
  "file\t.luai/manifest.lua\t6ff11b5b6c2be2d889446c12c7935b4dd622a5bb685a7ef34d787bdf861a9a38",
  "dir\t.luai/native",
  "file\t.luai/native/liblua-5.4.so\tf452186a357307daa99edf5f1f5178e6aee9ce38b51e30952de1814d8f5599e2",
  "file\tTHIRD_PARTY_NOTICES.md\t7e365c7923741104acd0bfa5d182ecb095418936e9e31eb9e75335fa68a46d28",
  "file\tmoon\t2eda4a9aa949ff47b13b19e3595fe82cd660430fef0fed55d6daffc687e6dcbe"
 ],
 "repro": {
  "dir": [
   [
    "2eda4a9aa949ff47b13b19e3595fe82cd660430fef0fed55d6daffc687e6dcbe",
    "build/r1/moon/moon"
   ],
   [
    "2eda4a9aa949ff47b13b19e3595fe82cd660430fef0fed55d6daffc687e6dcbe",
    "build/r2/moon/moon"
   ]
  ],
  "elsewhere": "2eda4a9aa949ff47b13b19e3595fe82cd660430fef0fed55d6daffc687e6dcbe",
  "onefile": [
   [
    "1df435a129b4edeca713ffd1bc7506d7cc62d8e4899db44ec0cc8dfc3ba6787f",
    "build/f1"
   ],
   [
    "1df435a129b4edeca713ffd1bc7506d7cc62d8e4899db44ec0cc8dfc3ba6787f",
    "build/f2"
   ]
  ]
 },
 "onefile_find": [
  "/tmp/luainstaller-onefile-1000",
  "/tmp/luainstaller-onefile-1000/e69cfd50e8e75b1b7bf646a7d97d0ebcecea0b09c3d04c9bc601b7969335d755",
  "/tmp/luainstaller-onefile-1000/e69cfd50e8e75b1b7bf646a7d97d0ebcecea0b09c3d04c9bc601b7969335d755/.luai",
  "/tmp/luainstaller-onefile-1000/e69cfd50e8e75b1b7bf646a7d97d0ebcecea0b09c3d04c9bc601b7969335d755/THIRD_PARTY_NOTICES.md",
  "/tmp/luainstaller-onefile-1000/e69cfd50e8e75b1b7bf646a7d97d0ebcecea0b09c3d04c9bc601b7969335d755/inner"
 ],
 "onefile_map": [
  {
   "size": 3611,
   "path": ".luai/build/RELINKING.adoc",
   "off": 10528
  },
  {
   "size": 43599,
   "path": ".luai/build/extractor.c",
   "off": 14144
  },
  {
   "size": 6627,
   "path": ".luai/build/generate-onefile-payload.lua",
   "off": 57760
  },
  {
   "size": 50934,
   "path": ".luai/build/launcher.c",
   "off": 64416
  },
  {
   "size": 814,
   "path": ".luai/build/payload-files.lua",
   "off": 115360
  },
  {
   "size": 35149,
   "path": ".luai/licenses/GPL-3.0-or-later.txt",
   "off": 116192
  },
  {
   "size": 7652,
   "path": ".luai/licenses/LGPL-3.0-or-later.txt",
   "off": 151360
  },
  {
   "size": 1068,
   "path": ".luai/licenses/Lua-MIT.txt",
   "off": 159040
  },
  {
   "size": 3967,
   "path": ".luai/manifest.lua",
   "off": 160128
  },
  {
   "size": 287400,
   "path": ".luai/native/liblua-5.4.so",
   "off": 164096
  },
  {
   "size": 2006,
   "path": "THIRD_PARTY_NOTICES.md",
   "off": 451520
  },
  {
   "size": 22472,
   "path": "inner",
   "off": 453536
  }
 ],
 "onefile_sum": {
  "files": 12,
  "payload": 465299,
  "total": 486280,
  "rest": 20981
 },
 "onefile": {
  "cache": "/tmp/luainstaller-onefile-1000/e69cfd50e8e75b1b7bf646a7d97d0ebcecea0b09c3d04c9bc601b7969335d755",
  "pid": [
   "pid started by the shell: 2792",
   "pid inside the program: 2792"
  ],
  "pid_cmd": "build/pid & echo \"pid started by the shell: $!\"; wait",
  "pid_dir": [
   "pid started by the shell: 2796",
   "pid inside the program: 2796"
  ]
 }
};
